### ISSUE TITLE
Remove Omnibus

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1304]
Chef Infra client [is effectively EOL](https://docs.chef.io/versions/), and Omnibus development [seems all but abandoned](github.com/chef/omnibus/issues).

This work should be completed in two phases to minimize disruption to existing Omnibus-based Firezone users:

## Phase 1

- [x] Improve docs around migrating to Docker
- [x] Add deprecation notice to the `postinst` script for Omnibus-based users to be warned of the deprecation

## Phase 2

- [x] Remove `omnibus/` build dir and related files/dirs
- [x] Remove CI pipeline build/publish
- [ ] Shut down self-hosted runners
- [ ] ~~Cloudsmith~~ EDIT: Keep the Cloudsmith packages published for existing instances to use

**Comment by mzs114** [comment]
Any plans to use the [Open Build service](https://build.opensuse.org/)? I mean having native packages may help the users.

**Comment by jamilbk** [comment]
@mzs114 Unfortunately there's a prohibitive amount of work involved in replacing Omnibus and omnibus-ctl with OBS and documenting and maintaining native packages going forward. Docker simplifies building, distributing, and maintaining the Firezone web service substantially for us, freeing up time and resources to improve Firezone.

See our [build from source documentation](https://docs.firezone.dev/deploy/advanced/build-from-source/) for instructions on building the Firezone portal itself if you'd like to build from source. Configuration can then be done via [environment variables](https://docs.firezone.dev/reference/env-vars).

**Comment by jamilbk** [comment]
This has been mostly complete in the `cloud` branch.
