### ISSUE TITLE
Merge blog and website into main repository

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1417]
# TODO

Refs https://github.com/firezone/marketing/issues/160

- [x] firezone/firezone#1418 
- [x] Update Github pages configuration to publish from www/
- [x] firezone/firezone#1419 
- [x] `docs.firezone.dev` and `blog.firezone.dev` with rewrites to `/docs` and `/blog` to our reverse proxy in Vultr
- [x] Add redirects for other paths in client-side redirects (e.g. /slack)
- [x] Update DNS of marketing site to GitHub Pages
- [x] https://github.com/firezone/marketing/issues/62
- [x] firezone/bizops#70
