### ISSUE TITLE
Migrate from GitHub Pages to a CDN for static site

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1434]
GitHub pages works well for simplicity's sake, but for things like server-side redirects and better visibility into 404s and such we'll want to migrate to a more full-featured static site hosting service like [Vercel](https://vercel.com) or [Netlify](https://netlify.com).

## TODO
- [ ] Move client-side redirects back to server-side redirects
- [ ] Update CI to publish to CDN instead of GitHub pages
- [ ] Deactivate GH pages
