### ISSUE TITLE
Linux GUI client

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1762]
Right now the auth token issued by the portal has a relatively short lifetime (1 day to 1 week), which means the user will need to re-authenticate to the Portal at least this often.

This means we will need to differentiate between a Linux client that expects user interaction and a Linux client that does not. We can differentiate between the two during the build phase such that we'll ship separate binaries/packages for a headless client and GUI client.

Most demand for Linux client will be for a Headless client, but this requires firezone/firezone#1770 as a prerequisite.

## Phase 1: Headless client
- [x] Headless binary that connects to `FIREZONE_API_URL` with a given `FIREZONE_ID` and `FIREZONE_TOKEN`
- [x] Refactor: rename `headless` to `linux` throughout the repo
- [x] README with developer-oriented documentation in `rust/connlib/clients/linux`
- [ ] Installing/upgrading/uninstalling user documentation (add a draft page in `website/`)
  - [ ] Sample docker compose
  - [ ] Sample systemd unit file
- [x] https://github.com/firezone/firezone/issues/1770
- [x] #3601
- [x] #3342 
- [x] Make sure logs work under sudo (might only be an issue for the GUI client)

## Phase 2: GUI client todo
- [x] Tauri packaging and CI
- [ ] Crash handling

**Comment by jamilbk** [comment]
@conectado Until we have mTLS OAuth for the headless clients, I think we could draw inspiration from the `gh` cli utility to manage auth from the CLI, specifically the `gh auth login` flow:

[![asciicast](https://asciinema.org/a/MTxXme6wQKCuxJuEwnop2gese.png)](https://asciinema.org/a/MTxXme6wQKCuxJuEwnop2gese)

**Comment by ivdok** [comment]
As a Linux GUI & CLI user, I would certainly prefer any custom clients to be available as a NetworkManager plugin, in addition to classic CLI binaries. This would enable easy setup for users and provide a robust framework for implementation.

**Comment by gvecchicert** [comment]
> As a Linux GUI & CLI user, I would certainly prefer any custom clients to be available as a NetworkManager plugin, in addition to classic CLI binaries. This would enable easy setup for users and provide a robust framework for implementation.

+1

**Comment by ReactorScram** [comment]
1.0.3 has the Linux GUI Client in it: https://github.com/firezone/firezone/releases/tag/1.0.3

**Comment by jamilbk** [comment]
We'll keep it there for now as an easter egg... I'll do more testing when I get a chance to write the docs for it #4925
