### ISSUE TITLE
1.0 Apple (iOS / macOS) Client

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1763]
## TODO

- [x] Apple project boilerplate
- [x] UI views
  - [x] Settings (for changing the login URL, and resetting app state)
  - [x] Prompt for Login URL
  - [x] Connected
  - [x] Disconnected
- [x] Auth
  - [x] Open a secure Webview to PortalMock URL, e.g. `http://macos-host-ip:4568/auth`
  - [x] Save resulting `client_auth_token` in KeyChain
  - [x] Call connlib with `portal_url` and `client_auth_token` to connect
- [x] firezone/product#588
- [x] firezone/product#625
- [x] firezone/product#586 
- [x] (swift): Settings pane: accept the team ID instead of portal URL (uuid or generic string)
  - [x] portal_url(stage): app.firez.one
  - [x] portal_url(prod): app.firezone.dev
- [x] (connlib): firezone/product#615
- [x] #1914
- [x] https://github.com/firezone/product/issues/647
- [x] (connlib-swift): Bubble DNS resolver strategy up to swift side (refs firezone/firezone#2043)
- [x] (swift): macOS `connecting` state with associated icon animation and timeout of ~15 seconds. "Resources unavailable"
- [x] (swift): iOS Resources Table UI view
- [x] #2048
- [x] #2018 
- [x] #2172
- [x] #2023 
- [x] https://github.com/firezone/firezone/issues/2037
