### ISSUE TITLE
epic: New Portal UI

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1764]
# Todo
```[tasklist]
- [x] Refactor codebase to separate business logic and presentation layers
  - [x] firezone/firezone#1479
- [x] Decide between Flowbite or Tailwind UI
- [x] Create new Phoenix web context to serve new UI
- [x] firezone/product#610 
- [ ] firezone/product#611
```

# Wireframes

https://balsamiq.cloud

**Comment by jamilbk** [comment]
@AndrewDryga Thinking we should go Flowbite for this. They have more components, seem to be iterating faster, and best of all: have corresponding Figma templates so we can unify client App UIs as well.

**Comment by jamilbk** [comment]
Half of the new UI has been stubbed in Tailwind (flowbite), @jamilbk to move back to finishing it week of ~6/12
