### ISSUE TITLE
1.0 Relay

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1765]
The Firezone Relay functions as a STUN/TURN server to facilitate NAT traversal for automatic holepunching.

Relay should only be expected to run on Linux with a recent kernel. We will likely need to host a managed deployment of regional Relays for Firezone cloud, but may want to offer users the ability to run their own Relay in the future.

## High-level requirements

1. [x] Implement STUN server: https://github.com/firezone/firezone/pull/1603
2. [x] **v1** Implement TURN server
	1. [x] https://github.com/firezone/product/issues/592:
       - https://github.com/firezone/firezone/pull/1604
       - https://github.com/firezone/firezone/pull/1610
	3. [x] Implement channel bindings: https://github.com/firezone/product/issues/593
	4. [x] Implement authentication: https://github.com/firezone/product/issues/594
5. [x] **v1** https://github.com/firezone/product/issues/596
6. [x] **v1** https://github.com/firezone/firezone/issues/1829
7. [x] https://github.com/firezone/product/issues/604
8. [x] https://github.com/firezone/product/issues/605
8. [x] https://github.com/firezone/product/issues/620
11. [x] firezone/firezone#1830
7. [x] https://github.com/firezone/firezone/issues/2040
9. [ ] Evaluate scope for additional attributes: `EVEN-PORT`, `DONT-FRAGMENT`, etc

**Comment by thomaseizinger** [comment]
Couple of thoughts / questions, now that I've explored the problem for a bit:

- There are quite a few implementations of STUN/TURN on crates.io, both in the form of libraries and binaries: https://docs.rs/releases/search?query=stun. Has there been an evaluation on whether any of them could be a fit for our problem?
- Does the requirement for authentication apply to STUN as well or just TURN? In theory, STUN requests are cheap but without some form of security, an attacker could still at least cause trouble by faking STUN error responses or otherwise disrupting the service. With this in mind and the fact that we control both ends of the connection, is do we necessarily need to use STUN as a protocol? Both the gateway and the clients already have a connection to the control plane, meaning it wouldn't be too difficult to extract their public ip from that connection. I am guessing that connection is authenticated and hence we don't need to worry about anyone tempering with the information we receive over it.

Following the standard makes reusing existing libraries / components easier. But if we build our own thing, the standard may be in the way and it could be easier to build our own thing? Unless I am mistaken, there are no components involved that we don't control (like browsers) where we'd have to follow the spec to make it work.

**Comment by conectado** [comment]
> Couple of thoughts / questions, now that I've explored the problem for a bit:
> 
> * There are quite a few implementations of STUN/TURN on crates.io, both in the form of libraries and binaries: https://docs.rs/releases/search?query=stun. Has there been an evaluation on whether any of them could be a fit for our problem?

I looked into full implementations of ICE and I didn't see anything well mantained outside of webrtc-rs. If you see something interesting we could use it. 

> * Does the requirement for authentication apply to STUN as well or just TURN? In theory, STUN requests are cheap but without some form of security, an attacker could still at least cause trouble by faking STUN error responses or otherwise disrupting the service. With this in mind and the fact that we control both ends of the connection, is do we necessarily need to use STUN as a protocol? Both the gateway and the clients already have a connection to the control plane, meaning it wouldn't be too difficult to extract their public ip from that connection. I am guessing that connection is authenticated and hence we don't need to worry about anyone tempering with the information we receive over it.

STUN should be also authenticated to prevent that kind of problems and TURN specification already have a STUN server and TURN request are already downgraded to STUN requests in ICE, I believe. 

if we deploy the STUN server along with the TURN server it's easier to make it compatible with clients, if we screw up with x-remote-ip headers(or similar) with our proxies STUN will still be working and we keep the ICE logic separated from the portal.

> Following the standard makes reusing existing libraries / components easier. But if we build our own thing, the standard may be in the way and it could be easier to build our own thing? Unless I am mistaken, there are no components involved that we don't control (like browsers) where we'd have to follow the spec to make it work.

I think following the standard is still the way to go to reuse libraries / components and building faster, we can always drop the standard in the future.

**Comment by thomaseizinger** [comment]
> > Couple of thoughts / questions, now that I've explored the problem for a bit:
> > 
> > * There are quite a few implementations of STUN/TURN on crates.io, both in the form of libraries and binaries: https://docs.rs/releases/search?query=stun. Has there been an evaluation on whether any of them could be a fit for our problem?
> 
> I looked into full implementations of ICE and I didn't see anything well mantained outside of webrtc-rs. If you see something interesting we could use it.

Okay, thanks! I had initially skimmed it and nothing looked too interesting.

I started writing it myself now and despite being simple, the binary format is annoying to emit on the wire.

I'll finish the stun server today and put it up for review. We can then decide whether we like it or it is too annoying.

> > * Does the requirement for authentication apply to STUN as well or just TURN? In theory, STUN requests are cheap but without some form of security, an attacker could still at least cause trouble by faking STUN error responses or otherwise disrupting the service. With this in mind and the fact that we control both ends of the connection, is do we necessarily need to use STUN as a protocol? Both the gateway and the clients already have a connection to the control plane, meaning it wouldn't be too difficult to extract their public ip from that connection. I am guessing that connection is authenticated and hence we don't need to worry about anyone tempering with the information we receive over it.
> 
> STUN should be also authenticated to prevent that kind of problems and TURN specification already have a STUN server and TURN request are already downgraded to STUN requests in ICE, I believe. 

Not sure if I follow the "downgraded" bit? STUN has attributes like message integrity that I think we'll need to implement (eventually) to be resilient against certain attacks.

> if we deploy the STUN server along with the TURN server it's easier to make it compatible with clients, if we screw up with x-remote-ip headers(or similar) with our proxies STUN will still be working and we keep the ICE logic separated from the portal.

Makes sense!

> > Following the standard makes reusing existing libraries / components easier. But if we build our own thing, the standard may be in the way and it could be easier to build our own thing? Unless I am mistaken, there are no components involved that we don't control (like browsers) where we'd have to follow the spec to make it work.
> 
> I think following the standard is still the way to go to reuse libraries / components and building faster, we can always drop the standard in the future.

Sounds good, thanks for clarifying!

**Comment by thomaseizinger** [comment]
I've read a bit more into detail on how the authentication mechanisms in STUN and TURN work. The summary is:

- There is an attribute called `MESSAGE-INTEGRITY-SHA256` which computes an HMAC over the entire message. Because STUN and TURN use the same basic message format, this can be used for both.
- This HMAC needs a shared-secret and the standard provides the option between a static secret and a challenge-based one. For the former, replay attacks are mitigated simply by expiring the secret yourself. In the latter, the server provides a nonce and can expire it at any time, forcing the client to authenticate itself again. In https://github.com/firezone/product/tree/main/architecture#access-protected-resource, there is talk about a "turn access token". I'd recommend that we implement the latter scheme for this token. It allows us to operate the relay more independently from the control plane, otherwise the control plane needs to act as a trusted intermediary for issuing and revoking tokens. All we need on the relay end is access to a username and password that is specific to the relay. I'd suggest that the control plane shares this once with the relay, i.e. "registers" the client with the relay during the initial setup.

Basically, the flow I am suggesting looks like this:

```mermaid
sequenceDiagram
actor CP
actor client
actor relay

client ->> CP: register
CP ->> CP: create relay credentials
CP ->> relay: register client
CP ->> client: return credentials

note over client, relay: STUN binding request

client ->> relay: initiate binding request (without credentials)
relay ->> client: response with challenge (nonce and realm)
client ->> relay: re-initiate binding request (authenticated using HMAC and credentials)
relay ->> client: send binding response
```

For the actual TURN operation, this is looks identical. We can expire the nonces at any point which should trigger a re-authentication in a standards-compliant STUN/TURN client. The HMAC is only a hash which is as cheap as it gets if we need to verify every relayed packet. Most notable, there is not double-encryption here which is what we want.

Looking at the libraries on crates.io, one that could be suitable is https://github.com/sancane/rustun/tree/main/stun-rs. I am not a big fan of the coding style because it is very object-oriented with a lot of moving pieces. Also, I am not sure how much emphasis was placed on performance. Based on intuition, I would have said that we don't want to unnecessarily copy buffers around too much.

**Comment by thomaseizinger** [comment]
> > * Does the requirement for authentication apply to STUN as well or just TURN? In theory, STUN requests are cheap but without some form of security, an attacker could still at least cause trouble by faking STUN error responses or otherwise disrupting the service. With this in mind and the fact that we control both ends of the connection, is do we necessarily need to use STUN as a protocol? Both the gateway and the clients already have a connection to the control plane, meaning it wouldn't be too difficult to extract their public ip from that connection. I am guessing that connection is authenticated and hence we don't need to worry about anyone tempering with the information we receive over it.
> 
> STUN should be also authenticated to prevent that kind of problems and TURN specification already have a STUN server and TURN request are already downgraded to STUN requests in ICE, I believe.

The RFC recommends to not require authentication for STUN because it is more work for the server to require and check the authentication than it is to fulfill the binding request: https://datatracker.ietf.org/doc/html/rfc8489#section-12

**Comment by thomaseizinger** [comment]
An alternative to the `Message-Integrity-Sha256` attribute for authentication would be to use OAuth2.0 as described in https://www.rfc-editor.org/rfc/rfc7635.txt. I have not yet looked into the details on whether that would have any advantages for us.

**Comment by AndrewDryga** [comment]
@thomaseizinger I actually suggested a similar scheme with an optimization:

1. When Relay connects to Control Plane it sends a `stamp_secret` which is just a random string (which will be stored in CP and Relay memory). The `stamp_secret` will be unique for every instance of the Relay and re-generated when Relay restarts (later we can rotate it at runtime);
2. Control Plane sends a `#{expires_at}:#{hash(expires_at <> relay_stamp_secret <> salt)}:#{salt}` as the STUN/TURN access token.
3. The Client or Gateway uses the received access token and sends it to STUN/TURN, the expiry date is signed so Relay will need to expire them. The lifetime of the relay access token will be the same as the authorized lifetime of a connection to the Gateway (so that they both expire at about the same time forcing the client to re-authorize).

One of the edge cases: admin goes to UI and removes User access to the Resource, which will send a message to the Gateway and disconnect the client. The Relay token will still be valid though, but we don't really care about it as the edge case is rather rare, worst thing you can do is to keep sending packets to the relay for the expiry date but Gateway won't receive them.

The pros:
- There is no additional communication between parties, CP doesn't act as a trusted source (just hashes/stamps authorizations), and Clients and Gateways don't need to send additional packets to the Relay;
- Like Wireguard does, the Relay can ignore any unauthorized packets and stay silent by default;
- We can add more arguments to the hashing function (random seed, remote IP of a client/gateway) to make it more secure, with minimal changes only to CP and Relay to support the change.

Con obviously is that custom code will be needed to support this scheme.

WDYT?

**Comment by jamilbk** [comment]
@AndrewDryga Using your approach I'm curious if it would be possible to replay packets intercepted from the Client to the Relay during the lifetime of the `stamp_secret`? Granted they won't be successfully decapsulated by the Gateway on the other side of the tunnel because WireGuard implements its own `nonce`. But if so, it means an adversary could DoS the Relay and/or Gateway with the replayed stream. The advantage to this approach I suppose like you mention is the elimination of the challenge-response authentication between Client and Relay, saving a couple roundtrips on each binding request.

The disadvantage could be that a replay attack is possible during the lifetime of a `stamp_secret`, requiring a Relay restart to expire. The attack vector here would be a malicious actor intercepting packets on public WiFi and replaying them to DoS an organization's Gateway or Relay until the affected Relay is rebooted.

The RFC's approach would require a couple more roundtrips on each binding request but with the added benefit that the Relay can disconnect a misbehaving client (or malicious middleman) at will without affecting the other clients because each client-relay channel is individually authenticated.

@thomaseizinger Am I understanding that right?

Depending on how long we want to maintain bound channels maybe the latter approach laid out by the RFC would be more suitable for us. I think the scheme @AndrewDryga came up with is essentially the RFC static shared secret scheme @thomaseizinger mentions:

> This HMAC needs a shared-secret and the standard provides the option between a static secret and a challenge-based one. For the former, replay attacks are mitigated simply by expiring the secret yourself.

**Comment by jamilbk** [comment]
If we deploy Relays geographically distributed (and later allow self-hosted Relays), then the challenge-response overhead could possibly be minimized.

**Comment by jamilbk** [comment]
cc @rbhitchcock for our chat Thursday (reminding myself)

**Comment by AndrewDryga** [comment]
@jamilbk The token will be unique per relay so the replay attack is easy to prevent: we can keep a hash map of all used tokens preventing their reuse (only for the lifetime of such tokens). For us using more RAM/disk should be a good tradeoff over adding more connection hops (increasing latency).

**Comment by jamilbk** [comment]
K I'll open a PR documenting this scheme to add to our architecture artifacts for others to refer to, and to make sure I'm understanding it.

**Comment by thomaseizinger** [comment]
> 2\. Control Plane sends a `#{expires_at}:#{hash(expires_at <> relay_stamp_secret <> salt)}:#{salt}` as the STUN/TURN access token.

This implies we don't use an HMAC right? Meaning the relay cannot detect whether a packet was tempered with since it left the client device.

In our situation, this might be okay because tempering with the payload means scrambling the wireguard paket which will be silently dropped by the gateway. It still feels a bit wrong but YMMV.

If we want to include an HMAC, I believe the design doesn't work because the client would need to know the secret and cannot just rely on a single token received from the CP. Also note that a custom scheme will require us to pick an unused attribute ID that we can use to carry the token in the STUN payload (not a big problem, just want to mention it for completeness' sake).

> Like Wireguard does, the Relay can ignore any unauthorized packets and stay silent by default;

I believe we can still achieve that to some degree:

- We can require all packets to carry identification, i.e. a `USERHASH` attribute and we silently drop all messages that are unauthenticated or carry a `USERHASH` that we are unaware of.
- We only trigger reauthorization if the token is expired but otherwise valid.

As a result, the relay will be silent unless you attempt to identify as a client that actually exists.

I think either solution will work. If you see enough benefits in the custom solution that it is worth the additional effort then it makes sense to roll with it.

From a timeline perspective, I am pushing this back anyway. I want to get the actual relay functionality working first. The authentication scheme doesn't matter for that.

**Comment by jamilbk** [comment]
@thomaseizinger Yes -- WireGuard's protocol handles tamper detection, so the only risk here is sending mangled packets to the Gateway.

At this point I should note that some networks and countries block WireGuard altogether (it's easy to detect with any DPI product), so we will eventually (v2?) need to provide an alternate transport firezone/product#528 that we can fallback to. 
The most likely candidate is TLS over 443 (HTTPS/WebSocket) as this has the least likely chance of being blocked.

Perhaps that would be the time to revisit the use of HMAC for data packets.

**Comment by jamilbk** [comment]
@thomaseizinger That said, I can't speak to the integrity of the STUN binding request and response messages themselves. In other security-sensitive STUN-enabled products I know TLS is used to secure these, but I'll defer to @conectado / @AndrewDryga for input here.

An exploit, security flaw, or potential for abuse found in our transport implementation would be very bad.

**Comment by thomaseizinger** [comment]
Documenting an out-of-band discussion with @jamilbk :

TURN has two operating modes: Embedded `DATA` attributes in a STUN packet or separate channels (only 4 byte overhead). The latter is never authenticated unless you run over an authenticated transport (like TLS). Thus, an attacker could spoof the packets as coming from a legit client and "participate" in the channel. This isn't a problem though because spoofing is already possible in IP based networks and there also is no amplification here because the attacker needs to send the packets themselves. Source: https://www.rfc-editor.org/rfc/rfc8656#name-fake-data

**Comment by conectado** [comment]
> > 2\. Control Plane sends a `#{expires_at}:#{hash(expires_at <> relay_stamp_secret <> salt)}:#{salt}` as the STUN/TURN access token.
> 
> This implies we don't use an HMAC right? Meaning the relay cannot detect whether a packet was tempered with since it left the client device.
> 
> In our situation, this might be okay because tempering with the payload means scrambling the wireguard paket which will be silently dropped by the gateway. It still feels a bit wrong but YMMV.
> 
> If we want to include an HMAC, I believe the design doesn't work because the client would need to know the secret and cannot just rely on a single token received from the CP. Also note that a custom scheme will require us to pick an unused attribute ID that we can use to carry the token in the STUN payload (not a big problem, just want to mention it for completeness' sake).

Can't we include the username or hash in the client's token and use that to generate an HMAC?

**Comment by thomaseizinger** [comment]
> > > 2. Control Plane sends a `#{expires_at}:#{hash(expires_at <> relay_stamp_secret <> salt)}:#{salt}` as the STUN/TURN access token.
> > 
> > 
> > This implies we don't use an HMAC right? Meaning the relay cannot detect whether a packet was tempered with since it left the client device.
> > In our situation, this might be okay because tempering with the payload means scrambling the wireguard paket which will be silently dropped by the gateway. It still feels a bit wrong but YMMV.
> > If we want to include an HMAC, I believe the design doesn't work because the client would need to know the secret and cannot just rely on a single token received from the CP. Also note that a custom scheme will require us to pick an unused attribute ID that we can use to carry the token in the STUN payload (not a big problem, just want to mention it for completeness' sake).
> 
> Can't we include the username or hash in the client's token and use that to generate an HMAC?

I guess we could treat the token as a "shared secret" between relay and client and include it in the HMAC.

**Comment by AndrewDryga** [comment]
@conectado @thomaseizinger I don't think that we can use a STUN access token for HMAC, the whole idea around the HMAC key is that both parties should know the secret key while no third party can intercept it. The STUN access token (hash I've described) will be sent in plaintext, which means you can intercept it and use it to generate valid HMAC for rogue packets.

The core RFC assumption is that both parties know about the some pre-provisioned username/password. And I think @thomaseizinger was thinking of something similar to the Diffie-Hellman algorithm in binding request/response here: https://github.com/firezone/firezone/issues/1765 (please correct me if I'm wrong and there is a simpler way). Otherwise, if the plan was to return the secret in plaintext that packet can be also intercepted to forge an HMAC signature.

So we have two ways to support HMAC:
1. The control plane generates a shared secret and sends it to both the Relay and the Client;
2. The Client makes a binding request to the Relay and negotiates through DH a shared secret.

Plus a bonus option of using asymmetric-key encryption, so that the client will know the public key of the STUN server and encrypt everything using it.

Considerations:
1. We might not need HMAC at all, the attack vector of flooding the STUN with packets will be effectively a DDoS attacking **the client**, which requires you to intercept the packets to copy them, which means that attacker in the same network, can just overload the client channel directly or do a lot of other nasty stuff;
2. If we decide to distribute secrets for HMACs from the control plane we will considerably increase connection latency, the relay must acknowledge new client keys before we provide them to the client so we will send multiple messages (one per relay) and await on all (or majority) of them;
4. Diffie-Hellman and asymmetric encryption are way heavier than hash to authenticate the packets, so we should be careful exposing them, it can be a DDoS attack vector by itself (calculating sha1 hash is way faster than any of those).

@jamilbk WDYT? I'd suggest ignoring the replay attacks right now and get back to it in a year or so.

**Comment by thomaseizinger** [comment]
> The STUN access token (hash I've described) will be sent in plaintext, which means you can intercept it and use it to generate valid HMAC for rogue packets.

I assumed that if we use an HMAC, we use it for all packets and thus it should never be sent in plaintext.

> So we have two ways to support HMAC:
> 
>     1. The control plane generates a shared secret and sends it to both the Relay and the Client;
> 
>     2. The Client makes a binding request to the Relay and negotiates through DH a shared secret.

I think there is a third way.

- The relay generates a secret value on startup.
- The portal retrieves this value and generates "credentials" for a user.
	- The username is the current timestamp describing the expiry of the credential, concatenated with a salt value. The username is an opaque string to the user.
	- The password is the secret value retrieved from the relay, hashed with the salt (and expiry?)
- Clients will authenticate to the relay using the RFC-specified "short-term credential mechanism"
- Upon receiving a packet, a relay decodes the "username", splitting it for timestamp and salt and can authenticate the message with its own secret value.

This is essentially your solution but modeled into the "short-term credential" mechanism of the spec which should allow us to reuse existing code / libraries.

**Comment by jamilbk** [comment]
So I like @AndrewDryga's approach of minimizing latency by using a shared secret from Relay -> Portal. We can piggyback off that request to [return the Relay's public IP address](https://github.com/firezone/product/issues/592#issuecomment-1542891762) @thomaseizinger. I also like @thomaseizinger's approach to use the RFC so we can avoid re-inventing the wheel and leverage existing libraries.

I also want to highlight a couple important business reasons we should probably follow the RFC as best we can:

* Enterprises deploying Firezone will be deploying it alongside existing firewalls, SIEMs, and other network appliances that may already have rules written for STUN/TURN traffic. This would include analyzing / verifying the channel binding authentication messages, potentially in an automated way.
* When we undergo a code audit and/or penetration test, a security researcher will need to verify our TURN authentication mechanism (and system architecture in general). The more we stick to existing standards, the faster and cheaper this process will be.

That said, after re-reading through the relevant parts of the RFC, I think @thomaseizinger's adapted approach inspired by @AndrewDryga's design primitives seems ideal.

A few more considerations:

Note that the HMAC authentication mechanism is _only_ used for [channel binding](rfc-editor.org/rfc/rfc8656#section-20-22) and not for application data, so the HMAC only applies during channel setup and refresh, which occurs every 10 minutes (by default -- clients can request longer lifetimes). The [`ChannelData`](https://www.rfc-editor.org/rfc/rfc8656#name-the-channeldata-message) message carries the application data and incurs only a 4-byte overhead to specify the Channel number:

#### ChannelData Message

```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|         Channel Number        |            Length             |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
/                       Application Data                        /
/                                                               /
|                                                               |
|                               +-------------------------------+
|                               |
+-------------------------------+
```

#### Channel Binding Request
(note the long-term credential mechanism is shown)
```
TURN                                 TURN          Peer         Peer
client                               server         A            B
  |--- ChannelBind request ----------->|            |            |
  |    Transaction-Id=0xE5913A8F46091637EF7D3328    |            |
  |    CHANNEL-NUMBER=0x4000           |            |            |
  |    XOR-PEER-ADDRESS=192.0.2.210:49191           |            |
  |    USERNAME="George"               |            |            |
  |    REALM="example.com"             |            |            |
  |    NONCE="obMatJos2gAAAadl7W7PeDU4hKE72jda"     |            |
  |    PASSWORD-ALGORITHMS=MD5 and SHA256           |            |
  |    PASSWORD-ALGORITHM=SHA256       |            |            |
  |    MESSAGE-INTEGRITY-SHA256=...    |            |            |
  |                                    |            |            |
  |<-- ChannelBind success response ---|            |            |
  |    Transaction-Id=0xE5913A8F46091637EF7D3328    |            |
  |    MESSAGE-INTEGRITY-SHA256=...    |            |            |
```

#### Channel Binding Refresh
(note the long-term credential mechanism is shown)
```
TURN                                 TURN          Peer         Peer
client                               server         A            B
  |--- Refresh request --------------->|            |            |
  |    Transaction-Id=0x0864B3C27ADE9354B4312414    |            |
  |    SOFTWARE="Example client 1.03"  |            |            |
  |    USERNAME="George"               |            |            |
  |    REALM="example.com"             |            |            |
  |    NONCE="oobMatJos2gAAAadl7W7PeDU4hKE72jda"    |            |
  |    PASSWORD-ALGORITHMS=MD5 and SHA256           |            |
  |    PASSWORD-ALGORITHM=SHA256       |            |            |
  |    MESSAGE-INTEGRITY-SHA256=...    |            |            |
  |                                    |            |            |
  |<-- Refresh error response ---------|            |            |
  |    Transaction-Id=0x0864B3C27ADE9354B4312414    |            |
  |    SOFTWARE="Example server, version 1.17"      |            |
  |    ERROR-CODE=438 (Stale Nonce)    |            |            |
  |    REALM="example.com"             |            |            |
  |    NONCE="obMatJos2gAAAadl7W7PeDU4hKE72jda"     |            |
  |    PASSWORD-ALGORITHMS=MD5 and SHA256           |            |
  |                                    |            |            |
  |--- Refresh request --------------->|            |            |
  |    Transaction-Id=0x427BD3E625A85FC731DC4191    |            |
  |    SOFTWARE="Example client 1.03"  |            |            |
  |    USERNAME="George"               |            |            |
  |    REALM="example.com"             |            |            |
  |    NONCE="obMatJos2gAAAadl7W7PeDU4hKE72jda"     |            |
  |    PASSWORD-ALGORITHMS=MD5 and SHA256           |            |
  |    PASSWORD-ALGORITHM=SHA256       |            |            |
  |    MESSAGE-INTEGRITY-SHA256=...    |            |            |
  |                                    |            |            |
  |<-- Refresh success response -------|            |            |
  |    Transaction-Id=0x427BD3E625A85FC731DC4191    |            |
  |    SOFTWARE="Example server, version 1.17"      |            |
  |    LIFETIME=600 (10 minutes)       |            |            |
  |    MESSAGE-INTEGRITY=...           |            |            |
```

**This highlights a couple important design implications:**

* Clients will need to be sure to refresh their channel bindings in time to avoid packet loss
* If a Client fails to successfully retrieve the access_token to authenticate a new channel binding, packet loss will occur. This places very strict uptime requirements on the Firezone portal to avoid substantial packet loss.

Based on the above points, **perhaps we should start with a much longer channel lifetime for launch like 120 minutes**. Clients could then begin refreshing channels at the 60-minute mark, giving us a whole hour of potential Control plane downtime before incurring packet loss. As we improve our uptime SLAs we could reduce this to improve security.

@AndrewDryga thoughts? cc @rbhitchcock

**Comment by AndrewDryga** [comment]
@thomaseizinger 

> I assumed that if we use an HMAC, we use it for all packets and thus it should never be sent in plaintext.

HMAC is just an integrity check using a hash function: `hash(key <> hash(key <> payload_to_sign))`. Both parties must know the same `key` before exchanging signed messages. So the question is how they will end up with the same secret key, I only know three ways I've described above (asymmetric encryption, prior exchange over secure channel, Diffie-Hellman).

> This is essentially your solution but modeled into the "short-term credential" mechanism of the spec which should allow us to reuse existing code / libraries.

Yeah, I also think that if we can send our access token over those two fields that would be better. So here I 100% trust you to decide what is the best way for relay to do it.

**Comment by AndrewDryga** [comment]
> Note that the HMAC authentication mechanism is only used for [channel binding](https://github.com/firezone/product/issues/rfc-editor.org/rfc/rfc8656#section-20-22) and not for application data

I missed that, it means that HMAC doesn't really solve replay attacks for us especially because our tokens are single-use. Probably the worst thing you can do is intercept a binding request packet, then send it from yourself which might let you send a packet to the gateway, which will not accept it anyways. It's not great but does not compromise us in any way.

So @jamilbk do we agree to use:
```
username = "#{expires_at}:#{salt}"
password = hash(expires_at <> relay_stamp_secret <> salt)
```
and ignore the HMAC for now?

> Based on the above points, perhaps we should start with a much longer channel lifetime for launch like 120 minutes. Clients could then begin refreshing channels at the 60-minute mark, giving us a whole hour of potential Control plane downtime before incurring packet loss. As we improve our uptime SLAs we could reduce this to improve security.

Agree here, for 1.0 I would keep those timeouts long and refresh early.

**Comment by AndrewDryga** [comment]
Thinking more of it I have one more idea: if the Panel is the one generating the payload for `ChannelBind` and `Refresh` requests it can use `relay_stamp_secret ` as a shared secret for HMAC too, which will be a trivial upgrade in the future (move packet building logic over to the panel and just have gateways and clients forward it). This will allow the relay to verify the integrity of messages coming from clients/gateways, but not vice versa.

I personally would vouch for not worrying about message integrity for our initial version just to move faster for now.

**Comment by thomaseizinger** [comment]
> So @jamilbk do we agree to use:
> ```
> username = "#{expires_at}:#{salt}"
> password = hash(expires_at <> relay_stamp_secret <> salt)
> ```
> and ignore the HMAC for now?

Maybe I am missing something but my understanding of the RFC was that the password acts as a shared secret for the HMAC between clients and relays.

It is not like HTTP basic auth were you actually send the password. We would only set the message-integrity attribute with an HMAC where the password acts as the shared secret.

**Comment by thomaseizinger** [comment]
If we make the clients aware of the username structure (i.e. the expiry timestamp), then the relay can hand out a few in advance, reducing the uptime requirements on the portal.

Not a must for 1.0 but good to have the option I guess :)

**Comment by jamilbk** [comment]
@thomaseizinger correct -- the [RFC states the HMAC key](https://www.rfc-editor.org/rfc/rfc8489#section-9.1) is the `password` for the short-term credential mechanism.

> If we make the clients aware of the username structure (i.e. the expiry timestamp), then the relay can hand out a few in advance, reducing the uptime requirements on the portal.

I was wondering this as well. In the future we could even generate usernames with lifetimes depending on the trust level of the client device.

@AndrewDryga The RFC doesn't allow us an option to omit the HMAC unfortunately, but it allows us to do it using Thomas' [proposed short-term credential scheme here](https://github.com/firezone/firezone/issues/1765)) (i.e. `relay_stamp_secret` as HMAC key like you suggest)

So I think we're all in agreement :-)

**Comment by AndrewDryga** [comment]
> Maybe I am missing something but my understanding of the RFC was that the password acts as a shared secret for the HMAC between clients and relays.

Hmm, I think I did not understand your suggestion from the first attempt. So you were thinking about something like this?

Panel -> Client:
```
salt = "#{expires_at}:#{salt}"
relay_access_token = hash(expires_at <> relay_stamp_secret <> salt)
```

Client -> Relay:
```
USERNAME = salt
MESSAGE-INTEGRITY-SHA256 = hmac(relay_access_token, payload)
```

Relay
```
[expires_at, salt] = String.split(USERNAME, ":", parts: 2)
secure_compare(MESSAGE-INTEGRITY-SHA256, hmac(hash(expires_at <> relay_stamp_secret <> salt), payload))
```

This will indeed work really well for us, let's go ahead with this scheme.

**Comment by conectado** [comment]
Just one note, do we need the salt?

We are already generating a random string in the relay I think that's not susceptible to rainbow tables.

**Comment by thomaseizinger** [comment]
> Just one note, do we need the salt?
> 
> We are already generating a random string in the relay I think that's not susceptible to rainbow tables.

The salt ensures that each client gets a different password.
