### ISSUE TITLE
[epic] Core Connectivity Library (Connlib)

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1766]
All Firezone endpoints (Gateways and Clients) will need to have the following core connectivity pieces implemented in (ideally) a cross-platform way:

# Todo
- [x] BoringTun encapsulation / decapsulation layers
- [x] ICE (first-pass) (STUN/TURN) connectivity
- [x] ~~Tunnel stacks for client platform(s)~~ Handled per-platform
- [x] WebSocket-based control plane connection
- [x] firezone/product#601 
- [x] firezone/product#586 
- [x] firezone/product#619
- [x] firezone/product#615 
- [x] firezone/product#616
- [x] firezone/product#618 
- [x] firezone/firezone#2043

# Component Diagram
https://github.com/firezone/product/blob/main/client-app-component-diagram.png

**Comment by jamilbk** [comment]
~~Don't think we need to track this as its own issue, will save the client apps for that~~

**Comment by jamilbk** [comment]
Closing this to track further in respective issues.
