### ISSUE TITLE
1.0 Android Client

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1767]
## Todo

- [x] Android project boilerplate
- [x] Add embeddable [wireguard tunnel library for Android](https://search.maven.org/artifact/com.wireguard.android/tunnel)
- [x] UI views
  - [x] Settings (for changing the login URL, and resetting app state)
  - [x] Prompt for Login URL
  - [x] Connected
  - [x] Disconnected
- [x] Auth
  - [x] Open a secure Webview to `http://10.0.2.2:4568/auth`
  - [x] Save `client_auth_token` in secure storage
  - [x] Call connlib with `portalURL` and `client_auth_token` to connect
- [x] firezone/product#588 (might not be needed if Android has a secure webview api)
- [x] firezone/product#626
- [x] firezone/product#586 
- [x] (kotlin): Settings pane: accept the team ID/slug instead of portal URL, then append to hardcoded portal_url
  - [x] portal_url(stage): app.firez.one
  - [x] portal_url(prod): app.firezone.dev
- [x] (kotlin): Resources Table UI view
- [x] (native): firezone/product#616
- [x] (kotlin): investigate how to update VpnService on the fly and repurcussions
- [x] #1970
- [x] #1969 
- [x] #2017
- [x] Minor cleanup (remove Sign In as Debug User button)
- [x] #2123
