### ISSUE TITLE
1.0 Beta Windows Client

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1768]
High-level issue to track work / discussion on the Windows client. Issues arranged in dependency order and should aim to be tackled top-to-bottom.

# Userspace application

- [x] Boilerplate / CI/CD #2715
- [x] Encrypted storage #2740
- [x] Git check-in and attribution for wintun #2758 
- [x] Tray icon and menu #2712
- [x] Permissions #2751
- [x] Connlib callbacks / integration #2716
- [x] Auth #2711
- [x] Settings #2714
- [x] Wintun packaging and install #2758
- [x] SplitDNS #2713
- [x] Auto-update #2717
- [x] #3017

See https://github.com/firezone/product/blob/main/architecture/connlib-client-ffi.md for an overview on the functions needed at the userspace <-> tunnel boundary.

# Tunnel

@conectado has most of this done already

# Headless operation

(Split to #3782)

**Comment by ReactorScram** [comment]
Added encrypted storage issue

**Comment by ReactorScram** [comment]
I split off the headless client since that won't be part of beta, so all remaining tasks are complete, we can treat any new tasks as new issues

**Comment by jamilbk** [comment]
🎉
