### ISSUE TITLE
1.0 Gateway

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1769]
# TODO

- [x] ~~STUN / TURN functionality~~ See firezone/firezone#1766
- [x] Masquerading / iptables control
- [x] Peer token/JWT expiration
- [x] firezone/product#623
- [x] firezone/product#624
- [x] #2030
