### ISSUE TITLE
1.0 Documentation

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2021]
### Tasks
- [x] Add `EOL` to top of legacy docs pages
- [x] New docs hosted at www.firezone.dev/kb
- [ ] WIP Sections:
    - [x] #2623
  - [x] Deploy
    - [x] Overview / Prerequisites
    - [x] Gateway
    - [x] Clients
    - [x] DNS
  - [x] Authenticate
    - [x] Google Workspace
    - [x] Generic OIDC
    - [x] Email (OTP)
    - [x] User / Group sync
  - [x] Administer
    - [x] Upgrading
    - [x] Backup / Restore
    - [x] Logs
    - [x] Troubleshooting
  - [x] User Guides
    - [x] macOS Client
    - [x] iOS Client
    - [x] Windows Client
    - [x] Android / ChromeOS Client
      - [x] Note #2261 
    - [x] Linux Client
  - [ ] Reference
    - [ ] Environment variables
    - [ ] Example deployments
      - [ ] Terraform: #2620
      - [ ] Homelab
      - [ ] GCP
      - [ ] Azure
      - [ ] AWS
      - [ ] On-prem
      - [ ] Kubernetes (TBD)
  - [ ] Learn
    - [ ] Architecture
      - [ ] DNS
      - [ ] Gateway
      - [ ] Relay
      - [ ] Resource
      - [ ] Client
      - [ ] Portal
    - [ ] Concepts
      - [ ] WireGuard
      - [ ] NAT Traversal
      - [ ] Open source
- [x] #1685 
- [x] #2727

**Comment by AndrewDryga** [comment]
Don't forget to mention that if Google does not return the refresh token indicated by IdP status "No refresh token provided by IdP and access token expires on..." - this means it sees that an app was reused, so you will need to delete the credential (client id/secret) and create a new one.

**Comment by jamilbk** [comment]
@AndrewDryga I was writing the Google workspace sync docs, and had a couple questions:

- What do we do to a Policy when a Group is removed from Google? Disable it? Nothing?
- What do we do about nested Groups/OUs? For example, the `Allcoms` group in our workspace has the `Engineering` and `Marketing` groups in it, but shows `0 Actors` in the Firezone portal.
