### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2027]
### User story

As a Firezone administrator for my team, I'd like to integrate Firezone into my automation workflow in order to manage Actors, Groups, Gateways, Resources, and Policies automatically as I provision and deprovision other infrastructure.

```[tasklist]
### Tasks
- [ ] https://github.com/firezone/firezone/issues/2365
- [ ] https://github.com/firezone/firezone/issues/2364
- [ ] https://github.com/firezone/firezone/issues/5200
- [ ] https://github.com/firezone/firezone/issues/2366
- [ ] https://github.com/firezone/firezone/issues/3045
- [ ] https://github.com/firezone/firezone/issues/3046
- [ ] https://github.com/firezone/firezone/issues/3047
- [ ] https://github.com/firezone/firezone/issues/2367
- [ ] https://github.com/firezone/firezone/issues/2368
- [ ] #2203
- [ ] #2209
- [ ] https://github.com/firezone/firezone/issues/2369
```

Purposefully leaving IdP and other Settings management out of the REST API for this issue -- can tackle that later.

**Comment by jamilbk** [comment]
After chatting with a customer, it's clear that the first priority for a REST API is the ability to manage actors, identities and groups so that these can be automated with a custom script for IdPs that don't support automatic user/group sync. Refs #3044
