### ISSUE TITLE
portal: Consistency polish before release

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2029]
I'll keep this list to not miss some minor yet important things before the final release of 1.0:

```[tasklist]
- [ ] #2032
- [ ] https://github.com/firezone/firezone/issues/3048
- [ ] https://github.com/firezone/firezone/issues/2133
- [ ] https://github.com/firezone/firezone/issues/2134
- [ ] https://github.com/firezone/firezone/issues/2138
- [ ] https://github.com/firezone/firezone/issues/2135
- [ ] https://github.com/firezone/firezone/issues/2141
- [ ] https://github.com/firezone/firezone/issues/2146
- [ ] https://github.com/firezone/firezone/issues/2143
- [ ] https://github.com/firezone/firezone/issues/2139
- [ ] https://github.com/firezone/firezone/issues/2140
- [ ] #2132
- [ ] https://github.com/firezone/firezone/issues/2142
- [ ] https://github.com/firezone/firezone/issues/2145
- [ ] https://github.com/firezone/firezone/issues/2136
- [ ] https://github.com/firezone/firezone/issues/2162
- [ ] https://github.com/firezone/firezone/issues/3689
- [x] Ecto Table-view filtering
- [x] Ecto Table-view sorting
- [ ] https://github.com/firezone/firezone/issues/4235
- [x] Move more assigns to `temporary_assigns` to reduce state stored
- [x] Remove usage of plan tables in favor of `<.table />` and `<.vertical_table />`
- [ ] https://github.com/firezone/firezone/issues/4237
- [x] Remove pagination and filter boxes
- [x] Use Account Slug consistently, with exception for IDP redirection
- [ ] OpenID Connect [conformance testing](https://openid.net/certification/connect_rp_testing/)
- [ ] https://github.com/firezone/firezone/issues/2161
- [ ] Add Postgres partitioning by list (`status`, and `deleted_at`) and range (for a large `audit logs` table do `PARTITION BY RANGE (created_at::date)` or something like that)
```

**Comment by AndrewDryga** [comment]
Closing as we have separate issues for remaining of tasks,
