### ISSUE TITLE
epic: connlib hardening

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2036]
More edge case testing of connlib in various network environments.

# Todo
- [x] Multi-plexing communications with multiple Resources behind the same Gateway over a single channel (i.e. single Peer)
- [ ] Benchmarks
  - [ ] Non-invasive flame graphs
  - [ ] Remove major bottlenecks
  - [ ] Jitter / Latency tests
- [ ] Test across client network changes
- [ ] Clients, Gateways, Relays counts stress testing
- [x] firezone/firezone#2028
