### ISSUE TITLE
1.0 Versioning / Release Strategy

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2041]
The portal API will need to remain stable as new features and messages are added.

We can version its API using a date-based convention that will allow us to easily create SLAs around support later on.  To meet SLA requirements, this endpoint would need to remain active for X months. `connlib` clients could then select the API version using a header in the WebSocket request, and we can check this header with a `Plug` to decorate the response header with `Deprecation` or `Sunset` headers as noted in #2203.

A versioning system can be implemented in our CI pipeline based on the above details:

- Each time we build on `main`, push built artifacts to a drafted release. The release version is `{{ major_version }}.{{ minor_version }}.{{ patch_version }}` where `major_version` is the release publication date in `YYYYMMDD` format, `minor_version` is bumped for backwards-compatible changes, and `patch` for bugfixes.
- Each build on main then deploys this build to `staging`
- A local `Makefile` script will be created to update all individual components with this major number upon a `make release`. The CI will read the major version, append the patch number and draft a new release on each successful build on `main`. This allows us the flexibility to promote any release we choose to `production` which could come in handy as we debug issues in production.
- Clicking `publish` for a drafted release will make that release public and trigger our CD pipeline to deploy to production.
- Creating a new major release would consist of the following steps:
  - `make release` to bump major

```[tasklist]
### Tasks
- [ ] https://github.com/firezone/firezone/issues/2211
- [ ] https://github.com/firezone/firezone/issues/2213
- [ ] https://github.com/firezone/firezone/issues/2210
- [ ] https://github.com/firezone/firezone/issues/2223
- [ ] #2202
- [ ] #1687
- [ ] https://github.com/firezone/firezone/issues/2208
- [ ] https://github.com/firezone/firezone/issues/2207
- [ ] https://github.com/firezone/firezone/issues/2205
- [ ] https://github.com/firezone/firezone/issues/2239
- [ ] #2477
- [ ] https://github.com/firezone/firezone/issues/2529
```

**Comment by thomaseizinger** [comment]
I think it is important to consider about what is actually being versioned. Some thoughts:

- Unless we release `connlib` to crates.io, I would not bother versioning its Rust API. It will be implicitly versioned together via the build of the clients. We can leverage the mono-repo here.
- The portal's API is likely the most important bit. I'd suggest to just not break that. Make new endpoints / channel messages instead.
- We'd need metrics on how many clients are still using old endpoints to make decisions on when we can remove stuff.
- Deprecated endpoints should return some kind of `Deprecation` header (see https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-deprecation-header). Clients should parse that and render an appropriate message to the user that they are using a client version that appears to be outdated.
- We can announce removal of endpoints with `Sunset` headers: https://www.rfc-editor.org/rfc/rfc8594#section-1.4. Similarly to deprecations, clients should parse that and issue appropriate messages to the user.
- I would not bother with using semantic versioning for client apps but use date-based versioning. Together with deprecation / sunset policies that makes it quite easy to say something like "we support clients for at least 6 months". Alternatively, follow the Firefox / Chrome model and release a new major version every X months but that is effectively the same as using dates for version numbers.

**Comment by jamilbk** [comment]
> * Unless we release `connlib` to crates.io, I would not bother versioning its Rust API. It will be implicitly versioned together via the build of the clients. We can leverage the mono-repo here.

Agreed. We've already ditched the binary packaging for Apple/Android upon moving into the monorepo. Much cleaner.

> * The portal's API is likely the most important bit. I'd suggest to just not break that. Make new endpoints / channel messages instead.

+1. I think we should err on the conservative side here. An entity or endpoint we expose in the API can never be removed. For our public REST API, we could use the standard version path prefix `/v1` for example.

> * We'd need metrics on how many clients are still using old endpoints to make decisions on when we can remove stuff.

Yeah, metrics will be key to have on day 1. We didn't have these (or didn't have enough of them) we originally launched, and it bit us hard. . Aside from the product intelligence we glean from these kinds of metrics, they're key for raising funding. Investors love to see metrics.

> * Deprecated endpoints should return some kind of `Deprecation` header (see https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-deprecation-header). Clients should parse that and render an appropriate message to the user that they are using a client version that appears to be outdated.
> * We can announce removal of endpoints with `Sunset` headers: https://www.rfc-editor.org/rfc/rfc8594#section-1.4. Similarly to deprecations, clients should parse that and issue appropriate messages to the user.

This seems fairly low-overhead to add and check for, and so I agree it should probably be there from day one. It will allow us to show the error "Your client is too old; please upgrade" and fail gracefully.

> * I would not bother with using semantic versioning for client apps but use date-based versioning. Together with deprecation / sunset policies that makes it quite easy to say something like "we support clients for at least 6 months". Alternatively, follow the Firefox / Chrome model and release a new major version every X months but that is effectively the same as using dates for version numbers.

This makes sense at first thought. We can internally version the WebSocket / control plane API with the same scheme. The public REST API used for automation can live separately and perhaps be more stable.

**Comment by thomaseizinger** [comment]
> For our public REST API, we could use the standard version path prefix `/v1` for example.

I'd suggest to not use path-based versioning. It gets too messy in my opinion. Once you add a `v2`, are you going to duplicate all sub-resources under the new `v2` path? e.g. if you have `/v1/users` and `/v1/resources` and you want to make  breaking change to `/users` you have `/v2/users`. Do you then also have `/v2/resources` which is equivalent to `/v1/resources`?

I'd suggest to just not make breaking changes and instead add fields to payloads and keep the old ones working.

You could also use a header. GitHub does that for example: https://docs.github.com/en/rest/overview/api-versions?apiVersion=2022-11-28

It would be fairly simple to intercept each request with a piece of middleware and check it against a certain date. This would allow us to measure, how many clients are still using old API versions and we can remove deprecated code after X amount of months. The middleware would then start rejecting these requests. That allows you to gradually move to a new version.

For example, if you want to rename a field in a payload, you first start serving both of them, then roll out updates to all clients and have them send a more recent date in the header. After X months or > % of clients using the new API, you simply remove the old field.

**Comment by jamilbk** [comment]
### Todo

Document how this process works in `MAINTAINERS.md` in wiki.

**Comment by AndrewDryga** [comment]
The way how we can deploy to production is to trigger a manually-reviewed deployment in `cd.yaml` when staging deployment passed and run a second `release-production.yaml` workflow for the production environment after approval, which will include everything we do for staging AND making a GitHub release with binaries.
