### ISSUE TITLE
Minimize data plane downtime during deploys

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2143]
```[tasklist]
### Tasks
- [x] https://github.com/firezone/firezone/issues/3350
- [x] #2915
- [x] #3352
- [ ] #3429
- [ ] https://github.com/firezone/firezone/issues/3937
- [ ] https://github.com/firezone/firezone/issues/3938
```

https://firezonehq.slack.com/archives/C04HRQTFY0Z/p1705962240688509

**Comment by jamilbk** [comment]
This is pretty much done

**Comment by jamilbk** [comment]
Reopened this due to some issues customers had recently that caused clients to lose TURN connectivity until they re-authenticate anytime relays are restarted
