### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by jefferenced** [CloudFire-LLC/cloudfire#2589]
**General notes**
```[tasklist]
- [ ] https://github.com/firezone/firezone/issues/2597
- [ ] https://github.com/firezone/firezone/issues/2588
- [ ] https://github.com/firezone/firezone/issues/2598
- [ ] https://github.com/firezone/firezone/issues/2599
- [x] ~Disconnect connections in real time when a policy revokes access~ duplicate of #2240
- [ ] https://github.com/firezone/firezone/issues/2583
```

**Sites**
```[tasklist]
* [ ] https://github.com/firezone/firezone/issues/2585
* [ ] https://github.com/firezone/firezone/issues/2584
```

**Gateways**
```[tasklist]
* [ ] https://github.com/firezone/firezone/issues/2586
* [ ] https://github.com/firezone/firezone/issues/2587
* [ ] https://github.com/firezone/firezone/issues/2620
```

**Resources**
```[tasklist]
* [ ] https://github.com/firezone/firezone/issues/2614
```

**Policies*
```[tasklist]
- [ ] https://github.com/firezone/firezone/issues/2601
```
 
**Clients**
```[tasklist]
* [x] ~Add filters~ Duplicate of https://github.com/firezone/firezone/issues/2029
* [ ] https://github.com/firezone/firezone/issues/2600
```

**Comment by AndrewDryga** [comment]
@jefferenced 

> Add a link to (and create) documentation for "Deploy to production" that illustrates deploying with e.g. Terraform

I think it's mostly a good docs issue because there are so many ways to deploy it with Terraform. We can show an example of how we can deploy it to our google cloud but every case will be different.

**Comment by AndrewDryga** [comment]
> Add an "access rules", "policies", or "who can access" section with list of user groups to Resource creation form to quickly create a policy. Make sure "None" can be selected.

I am not against this one but also not a big fan of the solution. Maybe it will be better to do the following:

- [ ] After the Resource is created show a page asking if the user wants to grant some users access to it (with options to say yes or "do it later"), and if the user confirms it - take him to the pre-filled resources form.
- [ ] On the Resources table show the ones without a policy with a link to quickly create a policy for it

I like this solution because we both educate users about Policies (which adds friction but I don't feel like it's a bad one) and have a long-term solution (because as soon as our Policy form has any other options Resources creating form will become unmanageable).

**Comment by bmanifold** [comment]
This thread got me thinking and raised a few question in my mind.  Has our policy engine been architected yet?  And closely related, do we have any timeline for when we want to roll out complex policies (i.e. policies that are more then just resource/actor group)?

If we haven't architected the policy engine yet and/or we don't have a tight timeline for a quick follow on to introduce complex policies, then I'm wondering if it might actually be better to not introduce policies, as a concept in the UI, at all during the beta launch and the initial GA launch?

We would still have policies on the backend, but if all we're going to have for a decent while is "simple" policies (i.e. actor group / resource matching) then it may be a smoother experience for the end user if they just choose which groups are allowed to access a resource right on the resource form itself.  Then when we do have complex policies we could unveil it as an awesome new feature that we're giving to the users.  This would make the UI simpler out of the gate and give us time to collect feedback as to which customers and how many are really pushing for more complex policies.

Curious about everyones thoughts.

**Comment by AndrewDryga** [comment]
@bmanifold We did architect a future version of the policies engine, that's why Policies were added in the UI and back-end in the first place. The plan was to split policy into two components: static and runtime. The static part is a group-resource connection, while runtime will have rules like `client_region in ["US"]` that are evaluated when a client requests a connection. (They can be encoded in JSON like `["and", [{field: "client.region", "cond": "in", ["US"]}]` mimicking Elixir AST.)

You can find one of the artifacts [here](https://github.com/firezone/product/tree/main/architecture#access-protected-resource) where an example shows runtime policy requiring a user to use a TOTP token to access a specific resource, this requirement is returned as connection error to the client and client should satisfy that requirement before actually joining.

My perception for Policies was that it's one of our key differentiators, when designing it we were hearing some bad feedback on JSON policies our competitors have and limitations for common use cases (separate fresh TOTP token for production DB access or geo-fencing, for example). We can remove them but then I would not keep them on the back-end either, it will be just a dead weight - we will have to always keep that table in sync with other parts, which can be a source of bugs.

**Comment by bmanifold** [comment]
Yeah, I wasn't trying to imply that Policies weren't important.  I agree that they could be a key differentiator for us.

Where my questions/concerns come in is that what you've described with the complex policies is essentially creating our own DSL and enforcement engine, which I don't believe we've started and will likely require some time to make sure it's done properly.  If that is going to take time, then I'm just wondering if it would be better to give the user an experience with less friction up front to try and get adoption faster.

As far as removing them from the backend if we don't show them on the frontend, I'm not sure I quite follow why it would be a problem to keep them on the backend as they are already implemented and they aren't all the complex at the moment.

**Comment by jamilbk** [comment]
@AndrewDryga @bmanifold Let's keep Policies in the UI for the time being and just add a link in the flash message after Resource creation to add a policy like mentioned on the grooming call.

That'll keep the REST API more consistent and also allow tiering based on Policies if we decide to go down that route.

Later we can improve the UX with #2614

**Comment by AndrewDryga** [comment]
@jamilbk it's already done in #2615
