### ISSUE TITLE
11/10/23 Runthrough Notes

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2631]
- [ ] Session token is expired/incognito windows
- [x] Make copy-paste button more prominent
- [x] #2597
  - [ ] Explain Sites
  - [x] Fix Gateways text
  - [ ] Not immediately clear that Gateways need network access to Resources
  - [x] Show Docker steps, including a step after running to output logs
- [x] Update Gateway page to not auto-redirect on Connection, instead just show a button
- [x] #2664
- [ ] Friction solved by https://github.com/firezone/firezone/issues/2331
- [ ] Not clear when you click Apply in client settings that you need to sign in from the menubar
- [ ] Friction solved by https://github.com/firezone/firezone/issues/2299
- [ ] Friction solved by https://github.com/firezone/firezone/issues/2588
- [x] Friction solved by https://github.com/firezone/firezone/pull/2615
- [x] #2639
- [x] #2632
