### ISSUE TITLE
UI Improvements [Dec 1 2023]

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2788]
- [x] Simplify Sign Up form
  - [x] Move Email to top of the form
  - [x] Pre-fill rest of fields from the email
- [x] Do not require people to re-type their email to first sign in, instead show a button to request email confirmation right away on "account created" page
- [x] #2798
- [x] Add account slug copy-paste button on the account settings page
- [x] #2791
- [x] Rename `Account ID` to `Workspace ID` on Clients and account settings?
- [x] Change the home form where you put your account slug to have `firezone.dev/` read-only prefix

**Comment by jamilbk** [comment]
> Rename Account ID to Workspace ID on Clients and account settings?

Was there a strong reason for this? I was thinking account ID makes sense since that'll also be the ID we can use for invoices and on sales contracts

**Comment by ReactorScram** [comment]
My feedback as a new user was that "Account ID" sounded like my user account, I had tried putting "ReactorScram" and my email in there at first. For individuals it'll make sense but if I was at a company I wouldn't know if account means the company account or my own account.

Someone said, "Wait, how does Slack do it?" Slack calls it a workspace and has a little prefix / suffix in the text field so you know it's supposed to be something.slack.com and not your gmail address.

**Comment by jamilbk** [comment]
@ReactorScram Ah, I see where you're coming from now. We used to call this `team id` but moved off that because `team` sounded smaller.

Let's keep it `account id` for now and perhaps add some UX improvements so that it's more clear in the future. The AWS console sign in comes to mind:

<img width="376" alt="Screenshot 2023-12-06 at 7 13 20 AM" src="https://github.com/firezone/firezone/assets/167144/2abd047e-0979-4df7-8d50-b95868c534de">
