### ISSUE TITLE
Tracking issue for replacing `webrtc-rs`

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#2966]
Tracking issue for the plan and progress of replacing `webrtc-rs` with our own, product-tailored connectivity library. For a prior discussion, see https://github.com/firezone/firezone/issues/1962.

### Design

After lots of prototyping and brainstorming with @conectado, I am proposing the following design: A `firezone-connection` crate that combines ICE, the wireguard state machine as well as STUN + TURN handling. `firezone-tunnel` can then use this abstraction to establish connections to other peers and on top of it, enforces the resource access policy and handles DNS.

```[tasklist]
### Implementation tasks
- [ ] https://github.com/firezone/firezone/pull/2965
- [x] Use docker health checks to monitor redis startup: https://github.com/firezone/firezone/pull/2965#discussion_r1435364144. Fixed in https://github.com/firezone/firezone/pull/3286
- [ ] Introduce new-type for ICE candidate: https://github.com/firezone/firezone/pull/2965#discussion_r1435373106
- [ ] https://github.com/firezone/firezone/pull/3268
- [ ] https://github.com/firezone/firezone/pull/3297
- [ ] https://github.com/firezone/firezone/pull/3413
- [ ] https://github.com/firezone/firezone/pull/3397
- [x] Investigate why we cannot hole-punch with just one symmetric NAT (research how and when reflexive peer candidates are used)
- [ ] https://github.com/firezone/firezone/issues/3372
- [ ] https://github.com/firezone/firezone/pull/3435
- [ ] https://github.com/firezone/firezone/pull/3474
- [ ] https://github.com/firezone/firezone/issues/3475
- [ ] https://github.com/firezone/firezone/pull/3528
- [ ] https://github.com/firezone/firezone/pull/3529
- [ ] https://github.com/firezone/firezone/pull/3530
- [x] Check why `snownet` continuously emits the warning `Unable to queue allocate because we've exceeded our backoffs` after it's a connection open for a while
- [ ] https://github.com/firezone/firezone/pull/3555
- [ ] https://github.com/firezone/firezone/pull/3556
- [ ] https://github.com/firezone/firezone/pull/3575
- [ ] https://github.com/firezone/firezone/pull/3581
- [ ] https://github.com/firezone/firezone/pull/3587
- [ ] https://github.com/firezone/firezone/pull/3589
- [ ] https://github.com/firezone/firezone/pull/3592
- [ ] https://github.com/firezone/firezone/pull/3590
- [ ] https://github.com/firezone/firezone/pull/3591
- [ ] https://github.com/firezone/firezone/pull/3631
- [ ] https://github.com/firezone/firezone/pull/3635
- [ ] https://github.com/firezone/firezone/pull/3634
- [ ] https://github.com/firezone/firezone/pull/3604
- [ ] https://github.com/firezone/firezone/issues/3377
- [ ] Document that `Transmit.src == None` MUST always go through the same socket (or model this better in the type system)
- [ ] Provide API for removing local interface (when it becomes unavailable), think about whether we need to do ICE restart, etc
- [ ] Decide how often we want to refresh STUN mappings
- [ ] Test IPv6 properly
```

```[tasklist]
### Upstream work (str0m)
- [ ] https://github.com/algesten/str0m/pull/418
- [ ] https://github.com/algesten/str0m/pull/421
- [ ] https://github.com/algesten/str0m/pull/423
- [ ] https://github.com/algesten/str0m/pull/419
- [ ] https://github.com/algesten/str0m/pull/422
- [ ] https://github.com/algesten/str0m/pull/425
- [ ] https://github.com/algesten/str0m/pull/447
- [ ] https://github.com/algesten/str0m/pull/449
- [ ] https://github.com/algesten/str0m/issues/413
- [ ] https://github.com/algesten/str0m/pull/452
- [ ] https://github.com/algesten/str0m/pull/455
- [ ] https://github.com/algesten/str0m/pull/458
- [x] https://github.com/algesten/str0m/issues/473
- [x] https://github.com/algesten/str0m/pull/471
```
```[tasklist]
### Follow-up work
- [ ] https://github.com/firezone/firezone/issues/3930
- [ ] https://github.com/firezone/firezone/pull/3682
- [ ] https://github.com/firezone/firezone/issues/3928
- [ ] https://github.com/firezone/firezone/issues/3926
- [ ] https://github.com/firezone/firezone/issues/3927
```

**Comment by conectado** [comment]
We will need to consider issues related to tunnel-over-tunnel. Ref: #3150

**Comment by jamilbk** [comment]
Good to close those and move remaining tasks to new issues?

**Comment by thomaseizinger** [comment]
> Good to close those and move remaining tasks to new issues?

Yes. I'll do some house-keeping here today.

**Comment by thomaseizinger** [comment]
> > Good to close those and move remaining tasks to new issues?
> 
> Yes. I'll do some house-keeping here today.

Done.
