### ISSUE TITLE
Refactor "STUN-only" feature

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3353]
After much testing and discussion with @thomaseizinger, we concluded if one client is behind a symmetric NAT, the connection must fallback to TURN.

Because of the likelihood of this happening for our target customer base (roaming clients), it's not reasonable to have a feature in the product that relies on holepunching to succeed. Instead:

- [ ] Remove "Direct routing" vs "Firezone-managed Relays" feature completely from product, marketing, and documentation (sorry @bmanifold)
- [ ] Add ability for Gateway to listen on a specific port. If specified, ensure that peer traffic always uses this port. This guarantees that our existing holepunching implementation will work by using the existing NAT mapping
- [ ] Document the above as "for direct connectivity, open a port..."
- [ ] Ensure a fair bandwidth policy is applied depending on customer tier. The easiest way to achieve this is probably deploy two kinds of Relays: _premium_ and _regular_. When clients/gateways connect, they're given the appropriate list. Changing your billing plan would then involve invalidating Relay credentials, requiring clients to fetch them again (#2040)

**Comment by thomaseizinger** [comment]
> * Ensure a fair bandwidth policy is applied depending on customer tier. The easiest way to achieve this is probably deploy two kinds of Relays: _premium_ and _regular_. When clients/gateways connect, they're given the appropriate list. Changing your billing plan would then involve invalidating Relay credentials, requiring clients to fetch them again

I think we can achieve this without any kinds of code change to the relay and clients. If premium vs regular are separate deployments, we can use `tc` on those machines to add a delay and thus decrease the throughput. We can also reduce the number of available ports which further reduced the required resources and allows us to run them on smaller machines.

Based on the tier, the portal would return a different relay but authentication and overall communication with the relay would stay the same.

**Comment by thomaseizinger** [comment]
This has some more implications if I am not mistaken. In particular, the portal currently passes us STUN-servers separately from TURN-servers. This separation exists all the way down to `snownet`. We don't need to change that now but if I understand this correctly, then separate STUN servers could be removed now, correct?

**Comment by jamilbk** [comment]
@thomaseizinger Yes, [here](https://github.com/firezone/firezone/blob/main/elixir/apps/api/lib/api/client/views/relay.ex#L42).

I suppose we could simplify this by combining the URIs, but then we wouldn't be able use them independently. Would that be an issue?

**Comment by thomaseizinger** [comment]
> I suppose we could simplify this by combining the URIs, but then we wouldn't be able use them independently. Would that be an issue?

What do you mean independently? If the "STUN-only" feature is removed from the product, why would we ever tell a client or gateway to "only" treat a relay as a STUN server? Because that is what we do currently. The "STUN servers" we send to the clients are just relays where the portal doesn't give you any credentials so the only message you can send to them are STUN binding requests.

**Comment by jamilbk** [comment]
Yes, today, it doesn't make much sense to separate them. I was thinking of cases where we may want them to be different servers (i.e. host all STUN servers on f1-micro instances in many regions, and host all TURN servers in OVH or some other provider with more friendly bandwidth costs). But if that isn't feasible / doesn't make sense from an engineering / operational perspective then I'm all for simplifying our implementation.

**Comment by thomaseizinger** [comment]
> Yes, today, it doesn't make much sense to separate them. I was thinking of cases where we may want them to be different servers (i.e. host all STUN servers on f1-micro instances in many regions, and host all TURN servers in OVH or some other provider with more friendly bandwidth costs). But if that isn't feasible / doesn't make sense from an engineering / operational perspective then I'm all for simplifying our implementation.

At present, we don't have separate STUN servers (although it would be trivial to implement). Each relay is a STUN server though (it will reply to STUN messages of type `BINDING`). In addition, a relay will also perform the functionality of `BINDING` (sending back the observed address) as part of receiving an `ALLOCATE` message. Thus, upon doing `ALLOCATE`, a client learns:

- Their server-reflexive address
- One or more relay addresses that have been allocated

The only difference here is that performing `ALLOCATE` requires credentials whereas `BINDING` does not. Thus, I think the decision should be based on whether or not we will give each connection at least one TURN server with credentials. If yes, sending separate STUN servers is superfluous. If no, we will need separate STUN servers so we can at least discover our server-reflexive address.

**Comment by thomaseizinger** [comment]
@jamilbk We are currently still maintaining the ability of separate STUN servers in `snownet` and `connlib`. Do we want to keep that around or should we delete that?

**Comment by jamilbk** [comment]
Yeah I don't think separating these is worth the tradeoff.

**Comment by thomaseizinger** [comment]
> Yeah I don't think separating these is worth the tradeoff.

Okay sounds good! Deleting code is always fun! :)
