### ISSUE TITLE
windows: Grep through code for TODOs and fix them or open new issues

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3513]
```[tasklist]
### Tasks
- [x] Open issues for ones that can't be solved immediately
- [x] Close ones that are easy to fix / already fixed
- [x] Open TODOs for missing SAFETY comments
```
