### ISSUE TITLE
Client Resource UX

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3514]
- [ ] ~~Ability to hide Resources from end-user view (move to advanced menu)~~ moved to #5123 
- [x] Add site labels
- [x] Update `address_description` to a `text_area` and accept Markdown content. Use case: adding rich text for clicking links and copy-pasting code snippets from the Resource menu.
- [x] Expanded -> Show:
- [x] ~~Determine sort ordering~~ use sort ordering from connlib
- [x] Fix UI on iOS
- [x] Fix UI on iPadOS
- [x] Fix update on Android
- [x] #4738
- [x] #4885

**Comment by ReactorScram** [comment]
What's the next step? Waiting for connlib to add the site to the resource struct?

**Comment by jamilbk** [comment]
- [ ] Update resource schema sent by portal to include `[{site.id, site.name}]` embedded in each resource (there can be mutliple)
- [ ] Display <site.name> labels for
- [ ] In the expansion on hover (desktop), show address and address description field with click-to-copy
- [ ] In the mobile UI resource list, clicking a resource should show a pop up with the Address and address description field with tap to copy

**Comment by jamilbk** [comment]
Still need to determine how to sort resources if they're in a flat list with just the site labels/badges attached to them.

**Comment by roop** [comment]
@jamilbk Can you show an example JSON with the newly added fields?

**Comment by jamilbk** [comment]
Customer feedback:

- Expose MTU to advanced users to fix issues like #4129 
- Expose route priority for CIDR/IP Resources in the client menu (checkbox works too) to handle route conflicts

**Comment by jameswinegar** [comment]
This would be useful as I want to know which sites are shared across users and then when they can or cannot connect.
