### ISSUE TITLE
linux(DNS): Technical debt

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3636]
Relating to https://github.com/firezone/firezone/pull/3629#discussion_r1487022289

These two PRs for DNS support on the Linux client will incur technical debt:
- Add env var to choose DNS control method https://github.com/firezone/firezone/pull/3629
- Control DNS via systemd-resolved https://github.com/firezone/firezone/pull/3628

The problem is that some code will live in `tun_linux.rs` and run in an async worker task, even though it should be up in the client:
- Reading an environment variable to choose the DNS control method
- Notifying systemd that the client is ready

There is already refactoring planned (as part of snownet integration maybe?) that would make it easy to get rid of this.
```[tasklist]
### Tasks
- [x] Decide how to handle empty list of DNS sentinel servers (Do nothing, the system should never have 0 DNS servers)
- [x] Remember to minimize permissions in the systemd service unit file
- [x] (failed) Try to remove sudo / root permissions for systemd service unit and bare exe
- [x] Move FIREZONE_DNS_CONTROL up to the client
- [x] Move systemd notification up to the client
```

**Comment by ReactorScram** [comment]
I think we can do the DNS control completely in connlib and then this will be less magical

**Comment by thomaseizinger** [comment]
We should be able to fix this by calling the callbacks on Linux too and do the DNS and route stuff in the client.

**Comment by ReactorScram** [comment]
Furthermore callbacks delenda est

**Comment by thomaseizinger** [comment]
> Furthermore callbacks delenda est

Yes! I am not sure if you are disagreeing with the above suggestion but I'll lay out my thinking anyway :)

To get rid of the callbacks, we need to first look at why we have them in the first place. We need to solve the same problem in a different way. I wrote about this in https://github.com/firezone/firezone/issues/4473.

For Android and Darwin, we _cannot_ do certain things in connlib but have to defer to the clients. That is what the callbacks do. If we want to remove them, we need to create a different signalling mechanism from connlib for the clients (events / state updates f.e.). The callbacks are a form of polymorphism and if we decide to remove them, it also makes sense to get rid of the polymorphism and achieve the platform-specific behaviour in a different way.

Thus, I think removing platform-specific code from connlib would be a good, first, incremental step towards removing the callbacks. If all that connlib is doing is calling the callbacks (so no route updates for Linux and Windows) inside `Tun`, it is much easier to move to a design where instead of calling the callbacks, we just emit an event because all the code that needs to happen as a result of the event is already in the correct place: in the client.

**Comment by thomaseizinger** [comment]
@ReactorScram #5111 completely fixed this, right?

**Comment by ReactorScram** [comment]
Yeah, looks like `sd-notify` moved up to the headless Client code too
