### ISSUE TITLE
Run Windows GUI and tunnel in separate processes

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3712]
Similar architecture to the other non-Rust clients.

Pros:

- enables seamless headless mode
- crash in GUI won't take down tunnel
- Bugs in Tauri won't affect tunnel process

Cons:

- software complexity
```[tasklist]
### Tasks
- [x] Figure out how to build an MSI that can install a Windows service #4903
- [x] Figure out how to build this in parallel without breaking `main` (The IPC service will always run and listen, the GUI will use an opt-in flag to use IPC instead of in-proc)
- [x] Move the device ID into `C:\ProgramData`
- [x] Remove security descriptor on deep link pipe
- [ ] Figure out how to secure named pipes
- [ ] Write new threat model for this
```

**Comment by ReactorScram** [comment]
For before beta or after beta?

**Comment by jamilbk** [comment]
Sorry, meant to mark it for GA
