### ISSUE TITLE
gui-client: Write threat model for Windows / Linux multi-process change

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3971]
Needed for #3712 and #3713 

Without the help of some OS-provided security like UWP, applications can't identify each other. So we might have to say, the Firezone client is open source, there's no way to prove that any exe isn't you running the Firezone client, so it's possible that malware could sign you out or connect to a resource, but it couldn't spy on your connection to a resource.

There is not much you can do about endpoint malware on a system where sandboxing apps is not the default IMO :(
```[tasklist]
### Tasks
- [ ] Automated test to prove we don't have this CVE https://emily.id.au/tailscale
- [ ] What if the Client sends a token to a malicious IPC service?
- [ ] What if a malicious program tries to connect to the IPC service?
```

**Comment by jamilbk** [comment]
On that note, here's a good example of issues that can arise: https://nvd.nist.gov/vuln/detail/CVE-2022-41924

**Comment by jamilbk** [comment]
Yeah, we should probably think through the IPC model here. We only want "authenticated" userspace processes to be able to control the tunnel process.

On Apple, we have Group Containers.

On Android, I think it uses the app's package id.

On Windows and Linux... ?

There's probably already lots of work in this space we could dig into to find current best practices.

**Comment by ReactorScram** [comment]
I skimmed through the CVE and https://emily.id.au/tailscale

Sounds like the bug was that the privileged tunnel process didn't check the Host header (which AIUI the browser engine controls and does not allow JS to override) and so a malicious webpage can impersonate the GUI client app.

I can handle that. But preventing one GUI app under the Windows or Linux user "Jane Doe" from impersonating another could be tricky. The solution I used for subzone won't work, since neither process is a child of the other.

On Linux we can use systemd to launch the tunnel and it can prove its identity by claiming a privileged D-Bus address or something, and Windows may have something similar, but proving the client's identity to the tunnel is trickier. I'll ask ChatGPT and search around.

**Comment by ReactorScram** [comment]
Some of this was satisfied by #4153

**Comment by ReactorScram** [comment]
Split this into Windows and Linux

**Comment by jamilbk** [comment]
This could wait til after GA.
