### ISSUE TITLE
Guidelines for FFI APIs

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4262]
This is an attempt to write down some of the learnings we had on iterating on the FFI for connlib.

- Functions exposed by connlib should be very targeted (i.e. just update the DNS servers).
- They may have severe side-effects, like rebinding the used UDP socket.
- It is the client's responsibility to only call these functions when appropriate.

With the above in mind, I'd propose the following changes:

1. Remove the debouncing from `set_dns`. `set_dns` has the side-effect of trashing all cached DNS queries and thus should only be called with the DNS servers that are being used. We can still make the function idempotent by checking internally, whether they are different from the last ones that got passed.
2. Re-bind local sockets in `reconnect`. This has the side-effect of essentially trashing all allocations on relays because TURN indexes everything by the client's 3-tuple. Clients should only call this if the primary interface changes.
```[tasklist]
### Tasks
- [ ] https://github.com/firezone/firezone/pull/4263
- [ ] Update Tauri client to only trigger `reconnect` when necessary
- [ ] Update Android client to only trigger `reconnect` when necessary
```

**Comment by thomaseizinger** [comment]
I am working on a PR for the connlib changes here: https://github.com/firezone/firezone/pull/4263.

Clients will have to be updated as a result.

Input welcome @firezone/engineering !

**Comment by jamilbk** [comment]
Keeping this open until we've tested the following:

- [x] #4305 
- [x] Session.reconnect is called only when needed on all clients
- [x] Session.set_dns is called only when needed on all clients

I think the last two might already be done?
