### ISSUE TITLE
bug(gui-client/windows): wintun failing to create adapter

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4765]
#### Describe the bug

The Client gets stuck signing in forever because wintun throws an error and connlib doesn't bubble it anywhere

#### To Reproduce

Not sure yet. I've seen it happen while restarting the app, as though the tunnel interface was not torn down fully

#### Expected behavior

- Expected wintun to work
- Expected errors to result in an error dialog or something that can reset the GUI to a usable state

#### Screenshots / Logs

```jsonl
{"time":"2024-04-24T14:18:06.7012667Z","target":"log","severity":"ERROR","logFile":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\wintun-0.4.0\\src\\log.rs","logLine":30,"logModulePath":"wintun::log","logTarget":"wintun::log","message":"WinTun: Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)"}
{"time":"2024-04-24T14:18:06.7019883Z","target":"log","severity":"ERROR","logFile":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\wintun-0.4.0\\src\\log.rs","logLine":30,"logModulePath":"wintun::log","logTarget":"wintun::log","message":"WinTun: Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC00002F0): The system cannot find the file specified. (Code 0x00000002)"}
{"time":"2024-04-24T14:18:06.745354Z","target":"firezone_tunnel::device_channel::tun_windows","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\device_channel\\tun_windows.rs","line":"70"},"severity":"ERROR","message":"wintun::Adapter::create failed, probably need admin powers: Failed to create adapter"}
{"time":"2024-04-24T14:18:06.7454742Z","target":"connlib_client_shared::eventloop","logging.googleapis.com/sourceLocation":{"file":"connlib\\clients\\shared\\src\\eventloop.rs","line":"199"},"severity":"WARNING","message":"Failed to set interface on tunnel: Failed to create adapter"}
```

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Version 1.0.0 (d656cd5)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ MSI from draft release

#### Additional context

Refs #4763

```[tasklist]
### Tasks
- [x] Ask wintun if the adapter already exists and log the result
- [x] Fault injection flag in the debug IPC service to replicate this
- [x] Can we retry with backoff?
- [ ] Can we get an `on_disconnect` or something to bubble this to the GUI?
```

**Comment by ReactorScram** [comment]
Replicated just now on the Windows Server 2022 VM while testing #5292. 
Connlib logs:

```jsonl
{"time":"2024-06-11T15:16:08.9480405Z","target":"firezone_headless_client::windows","logging.googleapis.com/sourceLocation":{"file":"headless-client\\src\\windows.rs","line":"279"},"severity":"INFO","clientPid":"5972","message":"Accepted IPC connection"}
{"time":"2024-06-11T15:16:08.948798Z","target":"firezone_headless_client::device_id","logging.googleapis.com/sourceLocation":{"file":"headless-client\\src\\device_id.rs","line":"29"},"severity":"DEBUG","id":"\"8c5be275-1187-4315-a0a8-ba4bf2daeeb8\"","message":"Loaded device ID from disk"}
{"time":"2024-06-11T15:16:09.3056911Z","target":"firezone_headless_client::dns_control::windows","logging.googleapis.com/sourceLocation":{"file":"headless-client\\src\\dns_control\\windows.rs","line":"71"},"severity":"DEBUG","resolvers":"[100.100.111.1, 192.168.1.1]"}
{"time":"2024-06-11T15:16:09.6646975Z","target":"phoenix_channel","logging.googleapis.com/sourceLocation":{"file":"phoenix-channel\\src\\lib.rs","line":"338"},"severity":"INFO","host":"api.firez.one","message":"Connected to portal"}
{"time":"2024-06-11T15:16:09.7238342Z","target":"firezone_tunnel::io","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\io.rs","line":"122"},"severity":"INFO","message":"Setting new DNS resolvers"}
{"time":"2024-06-11T15:16:32.4045679Z","target":"firezone_tunnel::device_channel::tun_windows","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\device_channel\\tun_windows.rs","line":"61"},"severity":"ERROR","message":"wintun::Adapter::create failed, probably need admin powers: Failed to create adapter"}
{"time":"2024-06-11T15:16:32.4046351Z","target":"connlib_client_shared::eventloop","logging.googleapis.com/sourceLocation":{"file":"connlib\\clients\\shared\\src\\eventloop.rs","line":"215"},"severity":"WARNING","message":"Failed to set interface on tunnel: Failed to create adapter"}
```

Restarting the GUI (and re-authing, which should be redundant) fixed it, but the user wouldn't know to do that if it's stuck in the signing-in state.

**Comment by ReactorScram** [comment]
Replicated for a customer

**Comment by jamilbk** [comment]
Possibly related to upgrading over a Client that's already running? Or a stale adapter left behind by an old instance? All I could think of.

**Comment by ReactorScram** [comment]
Yeah it's probably a stale adapter somehow. The official wintun example code tries to open the adapter and then falls back on creating it, which doesn't make sense to me, but if the adapter dropping doesn't work right, I guess it makes sense. So I may just copy them as the first step and log if that branch gets hit https://github.com/nulldotblack/wintun/blob/8988a0469e58b2ee5da3cbf3170ba6afdf0e02a1/examples/basic.rs#L17-L20

**Comment by ReactorScram** [comment]
I've gotten it to replicate but it will take longer to fix, the more I dig into it the more weird stuff I'm finding.
