### ISSUE TITLE
Client picks resource based on IP and port

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#4789]
Solves  https://github.com/firezone/firezone/issues/2030#issuecomment-2078027977

Currently the way we pick what gateway to send packets to works like this.

1. Select resource ID based on destination IP
2. Select gateway based on resource ID
3. Send packets to that gateway

For overlapping IPs on resources the selection is based on the longest match on the trie we use to store the IPs

However, now that we have traffic filters, we want to also consider that resources have associated port filters so how we  so we want to select the resource ID based on destination IP, protocol and destination port.

For this to work, we implemented #4994 so given the IP we could also know what's the FQDN that the packet is meant to be using and use that to resource select later on.

- [x] #4994
- [x] Portal sends traffic filters as part of the resource to the client
- [x] Read filters on the client from the portal (done i
- [x] Send TCP and UDP as part of the state machine tests
- [ ] Add resources filters to resources in state machine tests
- [ ] Rework resource lookup
- [ ] Encode new resource selection algorithm in state machine tests
- [ ] Consider sending ICMP errors from the client to the application for traffic that matches a resource but is filtered

**Comment by jamilbk** [comment]
Pre-requisite for #3133 

Refactor here is to let the Portal select the Resource to use when there can be multiple. `connlib` would only need to send the `dest:port` to the portal to hint what Resource to access, but ultimately it's up to the portal to resolve the Resource / Gateway to use appropriately.

**Comment by AndrewDryga** [comment]
@jamilbk I think the portal doesn't need to do that selection, the client already has all the filtering rules so it can decide which resource to use locally

**Comment by jamilbk** [comment]
@AndrewDryga The issue involving the refactor here is that the Everyone Group with access to only port 443 conflicts with the DevOps group with access to only port 22.

This requires moving filters to policies so that the portal can find a policy to match the resource + port for access attempted.

At least that's the design we settled on the last time we went over the issues here: https://docs.google.com/document/d/1qiR-dVssjQFM3Ah6B9n3M8xLXoXSvjL3eaucYjpAsTY/edit

**Comment by jamilbk** [comment]
Call 8/26/24

```[tasklist]
### Tasks
- [ ] ~Move traffic filters from resources to services~ (postponed on the offsite in favor of terraform module)
- [ ] ~When defining a policy, select which services to allow~ (postponed on the offsite in favor of terraform module)
- [ ] Connlib will need to determine which resource(s) to use based on packet, try them all (either one by one or in batch in the connection intent)
- [ ] In the portal warn the admin when they try to assign Resources with overlapping addresses / filters
- [ ] In connlib, find most specific match (address, ports, print warning in logs)
- [ ] Implement #6158 for handling address/port conflicts (TODO)
```

**Comment by jamilbk** [comment]
^ above needs to be in a separate epic

**Comment by thomaseizinger** [comment]
Customer just hit this. They had defined two resources with the same IP and different traffic filters. One for RDP traffic and one for DNS traffic.

When setting the upstream DNS server, nothing worked anymore because the client picked the resource with the RDP traffic filters and thus disallowed all DNS traffic.

**Comment by jamilbk** [comment]
Related: #12234

**Comment by jamilbk** [comment]
Hit again by another customer.

**Comment by thomaseizinger** [comment]
I am not sure if this is solvable in a way that isn't very confusing to the customer, at least for wildcard DNS resources. It is doable for CIDR and IP resources. For DNS resources, we need to assign the IP before seeing the actual application traffic. And once the IP is assigned, it is tied to a resource ID in the background.

We'd have to allow a DNS resource IP to point to multiple resources and depending on which traffic we are seeing, create a new authorization to the resource with the matching traffic filters.
