### ISSUE TITLE
Usage and uninstall docs for all Clients

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4963]
Uninstall / usage docs for Clients, in the existing `/kb/user-guides`. For the GUI clients, we should assume a non-technical user might be reading them. For the headless/CLI clients, we can assume the user has basic proficiency of the CLI.

Should cover:

- Prereqs / requirements
- How to install
- How to operate (wait to take screenshots until #3514 is complete, since menus will be changing in that)
  - Signing in
  - "You should see Resources you can access in the menu" -- one user hit this
  - Signing out
  - Troubleshooting / known issues
  - Viewing and clearing logs

```[tasklist]
### Tasks
- [ ] https://github.com/firezone/firezone/issues/4995
- [ ] https://github.com/firezone/firezone/issues/4925
- [ ] https://github.com/firezone/firezone/issues/4997
- [ ] https://github.com/firezone/firezone/issues/4998
- [ ] https://github.com/firezone/firezone/issues/4999
- [ ] https://github.com/firezone/firezone/issues/5000
```

**Comment by ReactorScram** [comment]
Should I do these in that order as separate PRs? Windows, Linux GUI, Linux Headless?

**Comment by jamilbk** [comment]
> Should I do these in that order as separate PRs? Windows, Linux GUI, Linux Headless?

Chef's choice. I can review it all in one PR if that makes it easier.
