### ISSUE TITLE
Tracking issue for potential bugs discovered by property-based state machine tests

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5036]
### Bugs
- [ ] https://github.com/firezone/firezone/issues/5727
- [ ] https://github.com/firezone/firezone/issues/5054
- [ ] Roaming from IPv4 only to IPv6 only does not invalidate previous server-reflexive candidate (we'd have to do that on the timeout of the BINDING request)
- [x] Client only has IPv4 connectivity and we only have IPv6 DNS servers (and vice-versa for IPv6 & IPv4)
- [x] DNS resource resolves to same IP as a CIDR resource: Breaks packet mangling of traffic to CIDR resources
- [ ] DNS resolution on gateway doesn't resolve to anything (for whatever reason), need to change `resolved_ips` to also emit 0 vec
- [ ] Adding / activating a DNS resource for an already resolved domain should invalidate DNS cache
- [ ] https://github.com/firezone/firezone/issues/6062

**Comment by jamilbk** [comment]
> Client only has IPv4 connectivity and we only have IPv6 DNS servers (and vice-versa for IPv6 & IPv4)

This can be removed I think. I'll resolve it with #5115
