### ISSUE TITLE
The IPC service on Linux and Windows should obey log level settings from the GUI

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5042]
Otherwise there is no way for users to set it
```[tasklist]
### Tasks
- [ ] Just have the GUI write a file that the IPC service reads
- [ ] Keep IPC connected all the time so we can set the log level even when signed out (#5279)
- [ ] Store log level on the IPC service side since it must boot before the GUI?
```
