### ISSUE TITLE
Autostart Linux GUI on boot

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5118]
```[tasklist]
### Tasks
- [x] Linux - XDG autostart #5361
- [ ] Windows - Startup folder
- [ ] https://github.com/firezone/firezone/issues/8916
```

**Comment by jamilbk** [comment]
We can just add to the docs the `systemctl` command to show how to enable it for now, so it's not blocked on #5119

**Comment by ReactorScram** [comment]
Should be easy, that can go in `deb_files` and install to `/usr/lib/systemd/user/` per https://wiki.archlinux.org/title/Systemd/User

**Comment by thomaseizinger** [comment]
AFAIK, GUIs are not started via systemd. If we want auto-start, we should put a `.desktop` file into `$XDG_CONFIG_HOME/autostart` (or a sym-link?)

See https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html.

**Comment by ReactorScram** [comment]
Yeah on another project the XDG autostart with a symlink to a file we can update (e.g. something in `/usr`) worked well. 

systemd user units need to get DISPLAY and XAUTHORITY somehow, Arch says: https://wiki.archlinux.org/title/Systemd/User#DISPLAY_and_XAUTHORITY

**Comment by ReactorScram** [comment]
Still waiting on #5119, right? Should I start that after connection roaming?

**Comment by jamilbk** [comment]
I think #5123 would be higher priority -- this is just a minor UX issue that users could work around for the time being but I think that one there's no workaround.
