### ISSUE TITLE
Add resource to favorites

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5123]
User story:

As a Client user I would like the ability to move some resources I don't particularly care about to a submenu, keeping only the ones I frequently need to click visible, like a favorites or bookmark list.
```[tasklist]
### Tasks
- [x] Break down into subtasks
- [x] Make up screenshots using bogus menu code to get everyone on the same page
- [x] Unit test for generating menus
- [x] ~~New on-disk format (atomic-saved JSON probably)~~ (just attached it to Settings)
- [x] Consider corner cases, like what if you favorite a Resource and then it's deleted? (it stays in the file until reset, which is harmless)
- [x] Unit tests for backwards compatibility with old on-disk formats
- [x] Plug in the new code
- [x] Implement for Kotlin #6107
- [x] Implement for Swift
```

Before:
<img width="592" alt="image" src="https://github.com/user-attachments/assets/ed2a990d-75f0-4f6a-b999-ce67288c39b7">

After (Showing favorited Resource):
<img width="586" alt="image" src="https://github.com/user-attachments/assets/075bd582-f616-4b5a-84ed-c9ba16c2b4ba">

After (Showing non-favorited Resource):
<img width="551" alt="image" src="https://github.com/user-attachments/assets/71fdf1f0-2b0e-4fa1-9ddd-cb4154816df3">

After (Showing nothing favorited yet):
<img width="582" alt="image" src="https://github.com/user-attachments/assets/fcb9d6a6-85af-435b-a085-d30bc24e0c0c">

**Comment by ReactorScram** [comment]
And we'll just store these in a file, maybe in the existing settings file, since there's < 100 Resources and they only change favorites a few times a day at most? (So SQLite would be overkill)

**Comment by jamilbk** [comment]
Yeah that's what I was thinking -- just use existing settings constructs, including reset functionality to reset to defaults (clear to empty list). I expect the user to probably update them a few times a week / month.

Main pain point currently is the list is just too long.

**Comment by jamilbk** [comment]
One thing to keep in mind since we're on the topic of settings is that #2667 will also need persistent storage in order to mark the internet resource as enabled/disabled.

So the schema might be something like:

`[ { "resource_id": string, "visible": boolean, "enabled": boolean } ]`

**Comment by ReactorScram** [comment]
~~The PR for this is waiting for design to finalize / other Clients to get PRs so that the Tauri Client doesn't get the feature half-baked before the other Clients.~~

For the persistent storage right now it piggybacks off of the advanced settings file, which is not intuitive to users, so we'll change it eventually.

Right now the PR is waiting to sync with other Client platforms

**Comment by ReactorScram** [comment]
Next step: Once #5846 is at a stopping point, try to implement similar changes for Kotlin and Swift Clients. Pair with Jamil when I get stuck. I can probably use the existing menu and settings code as reference for adding new menu options and ~~saving / loading file data.~~ using data stores

**Comment by jamilbk** [comment]
Swift/Kotlin have their "preferred" persistence mechanisms for storing data and probably won't like files. We could replicate the settings store as another store (favorites_store or something). Just an FYI.

**Comment by ReactorScram** [comment]
Ah so that's what they call it. That'll work!

**Comment by ReactorScram** [comment]
Status: Midway through macOS, haven't started iOS. Tauri and Android are merged into `main`

**Comment by jamilbk** [comment]
@ReactorScram where did we land with adding the "Reset favorites" button in Settings? That might be a needed UX addition for users who manage to get themselves into interesting favorites states. Or did you repurpose the "Reset settings" to do that?

**Comment by ReactorScram** [comment]
For Tauri, favorites are stored as part of the settings, so resetting the settings resets them https://github.com/firezone/firezone/blob/7151b0397abd63dd86c5588d9f21c2b07507e847/rust/gui-client/src-tauri/src/client/settings.rs#L15-L22

For Android, I might have forgot to put them anywhere, so I opened an issue #6293

**Comment by ReactorScram** [comment]
#6298 was the last one
