### ISSUE TITLE
refactor(headless-client): remove unnecessary layering

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5754]
Internal Slack discussion: https://firezonehq.slack.com/archives/C0575SD66E5/p1720055808381849

The headless Client was originally going to be one big binary that acts as both standalone Client and IPC service for the GUI. But since those have to ship separately and be updated by the package manager separately, we ended up unbundling them.

So now there's no need for the `main` functions in each binary to be thin wrappers around library functions, we can move the library functions that are specific to each binary up to that binary and make the library smaller.

```[tasklist]
### Tasks
- [ ] Inline GUI's `client.rs` into `main.rs`
- [ ] Consider splitting `firezone_headless_client` the binary crate from `firezone_headless_client` the library crate
- [ ] Evaluate whether it is worth to avoid a compile-time dependency between `firezone-gui-client` and `firezone-tunnel`
```
