### ISSUE TITLE
docs(gui-client): dev / test docs are outdated

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5877]
@conectado pointed this out, they don't explain how to run the Tunnel service
```[tasklist]
### Tasks
- [ ] Note that GUI can't run as admin even on Windows
- [ ] Update commands needed to build, prepare, and run (e.g. create socket dir, run Tunnel service)
- [ ] Add Tunnel service troubleshooting steps to user guides
- [ ] Mention warnings flag per #5893
- [ ] `sudo apt-get install systemd-resolved` needed on Debian 12
```

**Comment by jamilbk** [comment]
Yeah I was thinking about this too, thanks for noting it down.

Also in the published docs we could mention how to check if the Tunnel service is running and how to restart it.
