### ISSUE TITLE
Integrate with Sentry for crash logging and error reporting

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#6138]
Currently, we log unexpected errors or situations in the clients but we don't know about them until users report bugs.

For example: https://github.com/firezone/firezone/pull/6051#discussion_r1700784989

- [x] Sentry integration with GUI/headless clients #6782
- [x] https://github.com/firezone/firezone/pull/7105
- [x] https://github.com/firezone/firezone/pull/6946
- [x] https://github.com/firezone/firezone/issues/7099
- [x] https://github.com/firezone/firezone/pull/7151
- [x] https://github.com/firezone/firezone/pull/7152
- [x] https://github.com/firezone/firezone/pull/7331
- [x] Upload debug symbols for Android builds to Sentry
- [x] Upload debug symbols for Apple builds to Sentry
- [x] https://github.com/firezone/firezone/issues/8131
- [ ] Maybe remove Firebase crash reporting from Android client
- [x] Integrate Sentry's Swift SDK into Apple clients
- [x] https://github.com/firezone/firezone/issues/6815
- [x] https://github.com/firezone/firezone/issues/6816
- [x] https://github.com/firezone/firezone/issues/6822

**Comment by ReactorScram** [comment]
On the standup today we asked about doing Sentry for Gateways too, so that we can get metrics on who is using it in Docker vs. bare-metal deployments.

One concern came up: What if a user accidentally or maliciously sends a ton of events up to Sentry? How do Sentry's other customers handle that without being charged for bogus events?

**Comment by thomaseizinger** [comment]
> One concern came up: What if a user accidentally or maliciously sends a ton of events up to Sentry? How do Sentry's other customers handle that without being charged for bogus events?

The pricing doesn't change, AFAIK they will simply stop accepting events if you exceed them so there is no risk for additional charges.

It doesn't appear to be an issue in practice: https://github.com/getsentry/sentry/issues/48860#issuecomment-1546439315

**Comment by thomaseizinger** [comment]
> On the standup today we asked about doing Sentry for Gateways too, so that we can get metrics on who is using it in Docker vs. bare-metal deployments.

I'd suggest to use it for all customer-deployed software (so gateways too). Not so much for telemetry (which I am not sure Sentry can give us?) but because we want to know when gateways get into a buggy state or crash.

**Comment by thomaseizinger** [comment]
As a starting point, we can integrate Sentry into all non-appstore distributed builds, i.e. everthing non-Android and non-Apple.

That gives us still pretty good coverage, esp. for gateways and we don't need to declare anything in our AppStore manifests for now.

**Comment by ReactorScram** [comment]
For privacy concerns, should we have an env var like `FIREZONE_DISABLE_TELEMETRY=1`?

**Comment by thomaseizinger** [comment]
> For privacy concerns, should we have an env var like `FIREZONE_DISABLE_TELEMETRY=1`?

We can add it to the settings I guess? And have an env var for the headless client. I am not sure what the best way is to configure that on the IPC service. It would be nice to have Sentry initialised there from the start. Should we even initialise it twice or only report errors from the GUI?

**Comment by ReactorScram** [comment]
If I had to pick one process I'd rather have it in the IPC service, since all the complicated platform-specific networking like DNS control is there. 

But yeah I guess for the GUI it would have to be something like "Create this file on disk before installing the MSI" if users want an air-tight opt-out. Which, if it was me, I would.

**Comment by thomaseizinger** [comment]
If it is only in the IPC service, having Sentry wouldn't have notified of the last bug that we had with the wrong handling of missing Internet Resource.

To begin with, I think having to set it in the settings before the first launch is okay. In the future, we can add a pro-active dialog on startup. We can also add one right-away?

**Comment by thomaseizinger** [comment]
> To begin with, I think having to set it in the settings before the first launch is okay. In the future, we can add a pro-active dialog on startup. We can also add one right-away?

I guess it wouldn't be too bad to have a simple confirmation dialog at first launch? Some people will opt out but we will still have some data and it seems like the right thing to do.

**Comment by jamilbk** [comment]
> I guess it wouldn't be too bad to have a simple confirmation dialog at first launch? Some people will opt out but we will still have some data and it seems like the right thing to do.

Yeah, probably a good best-practice to follow

**Comment by ReactorScram** [comment]
Starting on it in #6782

**Comment by jamilbk** [comment]
Need to investigate these setups

- [ ] Apple/Android - need Swift/Kotlin
- [ ] GUI client
- [ ] Headless client

**Comment by jamilbk** [comment]
Going to groom this issue a bit to cover all the aspects for the integration if that's alright.

**Comment by thomaseizinger** [comment]
@jamilbk What is the status of being able to integrate Sentry with the Android and Apple clients?

**Comment by jamilbk** [comment]
> @jamilbk What is the status of being able to integrate Sentry with the Android and Apple clients?

What's stopping us? If a PR comes along I can look into making any app store listing changes. I think everyone in engineering is admin on the store accounts too so feel free to poke at it. Can walk through it together for knowledge transfer.

**Comment by thomaseizinger** [comment]
> What's stopping us?

AFAIK, only the agreement that we want to integrate it there too. Similar to the other clients, it would be always-on for now until we integrate it with the GUI to disable it.

If that is alright, then I'll prepare some PRs. I'd only integrate it on the Rust side for now, I don't think we need the Swift / Kotlin SDK.

**Comment by jamilbk** [comment]
> AFAIK, only the agreement that we want to integrate it there too.

Yep, that was the intention all along (hence tasks created for this issue)
