### ISSUE TITLE
Redesign Landing Page 

### ISSUE THREAD

**Issue by Patticatti** [CloudFire-LLC/cloudfire#6292]
- [x] Animate sliding logos
- [x] Restyle customer testimonials
- [x] Complete First Row of Blobs
- [ ] Second Row
- [ ] Rework pre-existing graphics to go inside blobs
- [x] Fix heading styling
```[tasklist]
### Tasks
- [ ] https://github.com/firezone/firezone/pull/6199
- [ ] https://github.com/firezone/firezone/pull/6291
- [ ] https://github.com/firezone/firezone/pull/6309
- [ ] https://github.com/firezone/firezone/pull/6252
- [ ] https://github.com/firezone/firezone/pull/6198
- [ ] https://github.com/firezone/firezone/pull/6318
- [ ] https://github.com/firezone/firezone/pull/6311
```

**Comment by jamilbk** [comment]
Done
