### ISSUE TITLE
IdP Refactor

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6294]
Upon chatting with customers we've discovered several UX issues that could prevent the IdP sync from smoothly scaling to larger use cases. This issue is focused on grouping / collecting them to handle those.

Current issues:

- Actors are duplicated from connecting an IdP, realizing it was a mistake, then deleting and recreating
- Duplicating actors makes it hard for them to use the Actor/Group parts of the UI
- Duplicating actors makes it harder for us to calculate active seat count
- Connecting an IdP sync ties it to a actual human, when that human leaves or changes departments the sync will need to be reconnected.

After discussing edge cases and the use cases, we could solve this with:

- Tie sync to service accounts
- Add an option when creating an IdP: `merge actors by email` boolean

### TODO

- [x] [Send alert email when IdP sync doesn't occur for X minutes | firezone#3976](https://github.com/firezone/firezone/issues/3976)
- [x] [Prompt admin to delete identities from deleted identity provider | firezone#6301](https://github.com/firezone/firezone/issues/6301)
- [x] [Tie IdP to service accounts, keep connection check working (+ docs, + settings) | firezone#6295](https://github.com/firezone/firezone/issues/6295)
- [x] Delete groups associated with identity provider when synced
- [x] Look into why everyone group members are deleted and reinserted on each sync
- [x] [Hide stale actors from view | firezone#6217](https://github.com/firezone/firezone/issues/6217)
- [x] Eliminate refresh token job in favor of dynamically fetch access_token on each job run

**Comment by jamilbk** [comment]
### Email OTP

```
[actors]
name<string>: NOT NULL

[actor_emails]
email<string>: NOT NULL
actor_id: references
account_id: references

[identities]
directory_provider_id<foreign_key_reference>: NULL
external_identifier<string>: NULL
given_name<string>: Joe
family_name<string>: Smith
middle_name<string>:
display_name<string>:
actor_id<foreign_key_reference>: references
```

### OIDC (JIT)

```
[actors]
name<string>: NOT NULL

[actor_emails]
email<string>: NOT NULL
actor_id: references
account_id: references

[identities]
directory_provider_id<foreign_key_reference>: NULL
external_identifier<string>: (sub claim)
given_name<string>:
family_name<string>:
middle_name<string>:
display_name<string>: Joe Luke Smith
actor_id<foreign_key_reference>: references
```

### IdP Sync

```
[actors]
name<string>: NOT NULL

[actor_emails]
email<string>: NOT NULL
actor_id: references
account_id: references

[identities]
directory_provider_id<foreign_key_reference>: (uuid)
external_identifier<string>: 0dfdsk232435hsZZXasdj
given_name<string>: Joe
family_name<string>: Smith
middle_name<string>: Luke
display_name<string>: Joe Luke Smith
actor_id<foreign_key_reference>: references
```

When inserting data from JIT provisioning or directory sync, we do:

1. Check for `identity_provider_identifier` match. If found, maybe add new email to actor's set of emails
2. If not found, look for actor with email matching incoming email. If found, upsert identity on the actor.
3. If neither holds, create a new actor + identity

**Comment by jamilbk** [comment]
Instead of using `JSONB` for actor_emails above, it makes more sense to just have a dedicated table for this, `actor_emails`. That way our index will be fast and efficient when used for the directory sync job.

**Comment by bmanifold** [comment]
> Instead of using `JSONB` for actor_emails above, it makes more sense to just have a dedicated table for this, `actor_emails`. That way our index will be fast and efficient when used for the directory sync job.

So are you saying we'd leave the `Actors` table as it is today then?

**Comment by jamilbk** [comment]
We need to move the `name` to identities otherwise yeah.

**Comment by jamilbk** [comment]
On second thought, we'll keep the `name` on actors, but add the `given_name, middle_name, family_name, display_name` fields to `identities` so that we can start populating these from the sync.

We'll continue to use `actors.name` as we do today, but now we'll have data on which name(s) are being synced and how to display or update those in the UI as necessary.

**Comment by jamilbk** [comment]
We need a plan to roll this incrementally in order to condense breaking changes into as few as possible:


- [ ] Add a unique index on `auth_providers.account_id, auth_providers.adapter WHERE adapter IN ['okta', 'google_workspace', 'microsoft_entra', 'jumpcloud']` to prevent creating multiple syncs of the same directory **today**
- [ ] Remove the ability to add additional `Email` identities to `Actors` in the UI to prevent further abuse **today**.
- [ ] (Proposal by @jamilbk): Add `auth_provider_id` to `directory_providers` and move sync fields to `directory_providers` and maintain the existing unique constraints on `auth_identities` and `actors_groups`, since we currently have duplicate `provider_identifiers` here (double-check this is the case). The goal here is to allow the new sync system to function effectively without needing to change the domain model substantially to collapse these duplicates.
- [ ] The desired end-state is to have a unique index on `actors.account_id, actors.email`
