### ISSUE TITLE
Create use case card graphics

### ISSUE THREAD

**Issue by Patticatti** [CloudFire-LLC/cloudfire#6329]
```[tasklist]
### Tasks
- [x] 2 fa
- [x] Block malicious DNS
- [ ] Manage access to a SaaS app
- [ ] Access a private network
- [ ] Access a private web app
- [x] Scale access to VPC resources
```

**Comment by Patticatti** [comment]
Link to assets:
https://www.figma.com/design/JedXtHJpQFgjlLXGcqJDkU/Prototype?node-id=15-288&t=3UZ6aCmeiuIXfPqv-1

**Comment by jamilbk** [comment]
This has been completed and is live!
