### ISSUE TITLE
New pricing page

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6378]
## High fidelity wireframe sections

```[tasklist]
- [x] New cards
- [x] Wireframe of pricing table
- [x] Fix pricing table
- [ ] FAQ
- [ ] Final CTA
```
```[tasklist]
### Tasks
- [ ] https://github.com/firezone/firezone/pull/6549
- [ ] https://github.com/firezone/firezone/pull/6557
```

**Comment by bmanifold** [comment]
@jamilbk, is this issue still relevant?
