### ISSUE TITLE
bug(rust/gui-client): Client will never sign in if started with no Internet

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6389]
```[tasklist]
### Tasks
- [x] Open PR to make the error louder (#6409)
- [x] Check if macOS has this problem (It does)
- [x] Check if Android has this problem
- [x] Check if iOS has this problem
- [x] Open PR to retry the connection whenever the network / DNS changes (#6414)
```

#### Describe the bug

If the GUI Client starts without Internet, it will never sign in and never raise the tunnel. This is because `PhoenixChannel::connect` fails and the Client never retries it

- Headless Client - This is intended behavior, PR #6409 documents it
- Rust GUI Client - This is a UX bug, PR #6409 changes it to a user-facing error
- macOS Client - If you start with a token and no Internet, the macOS Client appears signed out. When you gain Internet, you are still signed out. When you then restart the Client, you sign in automatically
- Android - Restart the phone in Airplane mode to close and re-open Firezone. Then disable Airplane mode. Firezone will not work until you open the app.
- iOS - Restart the phone in Airplane to close and re-open Firezone. Then disable Airplane mode. Firezone will not work until you enable the VPN config.

#### To Reproduce

1. Sign in to the Client
2. Quit the Client
3. Disconnect from the Internet
4. Start the Client
5. Wait 10 seconds or so
6. Connect to the Internet

The IPC service logs will have a bunch of errors in them and the Client will never sign in.

The headless Client has a similar problem, it bails out if you start it with no Internet.

#### Expected behavior

- As a user, expected the sign-in to resume once Internet is gained
- As the Client app, expected the IPC service to respond with `on_disconnect` or something if requests are failing because there's no connlib session
- As the IPC service, expected an `on_disconnect` from connlib if the portal connection fails permanently

Otherwise this will interfere with auto-starting the GUI, since users will have to reset the connection if the computer started without Internet.

#### Screenshots / Logs

Bad log:

```
2024-08-21T17:05:34.294353Z  INFO firezone_headless_client::ipc_service::ipc::platform: Accepted IPC connection client_pid=12324
2024-08-21T17:05:34.295758Z DEBUG firezone_headless_client::device_id: Loaded device ID from disk id="0a9ba5c0-7edb-4f3a-a2a1-b4d011755849"
2024-08-21T17:05:34.296576Z ERROR firezone_headless_client::ipc_service: Error while handling IPC message from client error=No such host is known. (os error 11001)
2024-08-21T17:05:34.304275Z ERROR firezone_headless_client::ipc_service: Error while handling IPC message from client error=No connlib session
2024-08-21T17:05:47.953716Z ERROR firezone_headless_client::ipc_service: Error while handling IPC message from client error=No connlib session
2024-08-21T17:05:48.454505Z ERROR firezone_headless_client::ipc_service: Error while handling IPC message from client error=No connlib session
```

The last few errors are from the GUI trying to tell the IPC service about network / DNS change events, but the IPC service won't listen because it's not signed in.

Good: (If the GUI started with Internet)

```
2024-08-21T17:07:20.441786Z  INFO firezone_headless_client::ipc_service::ipc::platform: Accepted IPC connection client_pid=15376
2024-08-21T17:07:20.443573Z DEBUG firezone_headless_client::device_id: Loaded device ID from disk id="0a9ba5c0-7edb-4f3a-a2a1-b4d011755849"
2024-08-21T17:07:20.486350Z DEBUG phoenix_channel: Connecting to portal host=api.firez.one user_agent=Windows/10.0.22631 connlib/1.2.0 (x86_64)
2024-08-21T17:07:20.486627Z DEBUG new{mtu=1280}: firezone_bin_shared::tun_device_manager::windows: wintun.dll path path="C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\dev.firezone.client\\data\\wintun.dll"
2024-08-21T17:07:20.493580Z DEBUG firezone_bin_shared::windows: Resolved best route outside of tunnel interface src=192.168.1.12 dst=34.160.64.79
2024-08-21T17:07:20.623380Z  INFO phoenix_channel: Connected to portal host=api.firez.one
2024-08-21T17:07:20.686105Z DEBUG firezone_tunnel::client: Updating DNS servers mapping={100.100.111.1 <> 1.1.1.1:53, fd00:2021:1111:8000:100:100:111:0 <> [2606:4700:4700::1111]:53}
```

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ GUI Client, macOS Client, possibly others if this is a connlib issue
- _Firezone Version (e.g. 1.0.0 or N/A):_ 16da501 (tip of `main`)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11, probably Ubuntu, possibly others
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ CI-built MSI

#### Additional context

Discovered while testing #6382

**Comment by jamilbk** [comment]
Good catch. I'll label to prioritize.

**Comment by ReactorScram** [comment]
Discussed with Gabi and Thomas
- Make the IPC service send a `Result` back to the GUI for the `connect` IPC request
- If the GUI gets a "No Internet" error back, it should retry and show a "Waiting for Internet" or something
- Document that Headless' behavior is intended, Headless should bail out and allow its manager (typically systemd) to restart it

We won't change anything in `phoenix-channel` or `connlib` for this, and we'll put off Swift and Kotlin fixes until after `rust/gui-client` is fixed

**Comment by ReactorScram** [comment]
The bug seems to replicate on macOS, Android, and iOS. I'm not sure how much we can fix it on Android and iOS since "start" and "stop" are oddly defined on phones.

**Comment by jamilbk** [comment]
> The bug seems to replicate on macOS, Android, and iOS.

I think I'm missing something - is this when starting the client into a signed-in state?

**Comment by ReactorScram** [comment]
Yeah.

Given we have a token on disk, and there's no Internet access, when we start the Client and then gain Internet access, then the Client should sign in, right?

Instead it sticks in some suspended state where it has the token and has Internet but Firezone is not running, until you do some manual intervention like opening the app on Android or enabling the VPN setting on iOS.

**Comment by ReactorScram** [comment]
I had documented that but I guess GitHub ate some of my edits.

**Comment by jamilbk** [comment]
> when we start the Client and then gain Internet access, then the Client should sign in, right?

Hm, I suppose so. This is going to be tricky to do in macOS and iOS (and probably Android too) since the network monitor runs in the tunnel thread. We need it there so that the service can run without the GUI.

What we would have to do here is have two network monitors - one basic one in the GUI process that checks for offline/online, and the current more detailed one.

On Apple the `reasserting` state means `offline`, so we can move that condition from the tunnel to the GUI process.
