### ISSUE TITLE
Refactor swift model/view

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#6554]
```[tasklist]
### Tasks
- [ ] Make the `Store` as small as possible to contain only `Resource` `InternetResourceEnalbed` and `FavoriteResources`
- [ ] Move everything else from `Store` into `TunnelManager`
- [x] Move the menu bar into swift ui(drop older than macos 13 support)
- [ ] Write unit test for the swift ui components using only the store
```
