### ISSUE TITLE
Offsite To-Do

### ISSUE THREAD

**Issue by Patticatti** [CloudFire-LLC/cloudfire#6600]
```[tasklist]
### Tasks
- [x] Sales Deck Template
- [x] Import theme colours to sales deck
- [ ] Create slide template structure for main "types"
- [ ] Add cool toned greys colours to tailwind config
```

**Comment by thomaseizinger** [comment]
Is this still relevant @jamilbk ?
