### ISSUE TITLE
Policies UX Proposal

### ISSUE THREAD

**Issue by Patticatti** [CloudFire-LLC/cloudfire#6686]
```[tasklist]
### Tasks
- [ ] Add group name -> resource instead of the ID string to be consistent
- [ ] Add creation date maybe?
- [ ] Make Status have green dot if active, similar to other pages
```

**Comment by thomaseizinger** [comment]
Is this still relevant @jamilbk ?

**Comment by jamilbk** [comment]
Yeah, this needs to be addressed at some point.

**Comment by bmanifold** [comment]
These tasks have either been completed or are no longer relevant with the new UI refactor completed.
