### ISSUE TITLE
Move `Internet Resource` into dedicated `Internet Site`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6834]
- [x] #6905
- [x] Update docs regarding internet resource, [mention this comment](https://github.com/firezone/firezone/pull/6905#issuecomment-2403605014)
- [x] DB migrations
- [x] Move internet resource from standard resource lists to its own section
- [x] Remove sections that don't make sense in Internet Resource
- [x] Blog post
- [x] Email announcement
  - [x] Add DB constraint to enforce other resources can't be connected to internet sites
  - [x] Add DB constraint to enforce the internet resource can't be connected to other sites
  - [x] Ensure API updated to reflect this restriction
