### ISSUE TITLE
Tauri v2

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#7005]
Windows:
- Crashes when clicking the tray icon, with exit code `0xc000041d`, might be similar to https://github.com/tauri-apps/tauri/issues/781 or https://github.com/tauri-apps/tauri/issues/10987
- Needs exe / MSI signing

Ubuntu 22.04:
- Window decorations, including the close button, don't work right in Wayland. There is a workaround by setting `GDK_BACKEND=x11`, seems to be a bug in Tao https://github.com/tauri-apps/tauri/issues/10686

```[tasklist]
### Tasks
- [x] Extract PR to add new Rust projects to `setup-rust` list for Windows
- [x] Correct apt-get prereqs in README files
- [x] Ensure every version has the mark for the Makefile to find it
- [ ] Pin latest Ubuntu 20.04-supporting GUI Client in docs and changelog
```

**Comment by thomaseizinger** [comment]
This has been shipped.
