### ISSUE TITLE
Tracking issue for performance optimisations

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#7452]
- [x] Move UDP sockets to separate thread
- [ ] Multi-threaded UDP sockets with `SO_REUSEPORT`
- [ ] Investigate cache misses
- [ ] Buffer size optimisations

**Comment by thomaseizinger** [comment]
> * Multi-threaded UDP sockets with `SO_REUSEPORT`

Maybe just 1 other thread with another socket is good enough to offload the sending.

**Comment by thomaseizinger** [comment]
Investigate syscalls with https://github.com/JakWai01/lurk.

**Comment by thomaseizinger** [comment]
I think using a completion-based IO runtime would actually give us a lot of benefits. We already have an architecture in place where we have separate threads for TUN IO and (soon) UDP IO. Starting a completion-based IO runtime on each one of those would be super easy. For example: https://docs.rs/compio/latest/compio/index.html

I did some experiments for doing this for the TUN device and it works quite well:

```rust
pub fn send_recv_tun<T>(
    fd: T,
    inbound_tx: mpsc::Sender<IpPacket>,
    mut outbound_rx: flume::r#async::RecvStream<'static, IpPacket>,
    _: impl Fn(RawFd, &mut IpPacketBuf) -> io::Result<usize>,
    _: impl Fn(RawFd, &IpPacket) -> io::Result<usize>,
) -> Result<()>
where
    T: AsRawFd + 'static,
{
    compio::runtime::Runtime::new()
        .context("Failed to create runtime")?
        .block_on(async move {
            let fd = AsyncFd::new(fd).unwrap();
            let write_fd = fd.to_shared_fd();
            let read_fd = fd.to_shared_fd();

            let read_inbound_packets = compio::runtime::spawn(async move {
                loop {
                    let (len, buf) =
                        compio::runtime::submit(Recv::new(read_fd.clone(), IpPacketBuf::new()))
                            .await
                            .map_buffer(|b| b.into_inner())
                            .unwrap();
                    let packet = IpPacket::new(buf, len).unwrap();

                    inbound_tx.send(packet).await.unwrap();
                }
            });
            let write_outbound_packets = compio::runtime::spawn(async move {
                loop {
                    let ip_packet = outbound_rx.next().await.unwrap();
                    let write_fd = write_fd.clone();

                    // There is no need to wait for one `Send` to complete, just spawn away and continue.
                    compio::runtime::spawn(async move {
                        let (_written, _buf) =
                            compio::runtime::submit(Send::new(write_fd.clone(), ip_packet))
                                .await
                                .map_buffer(|b| b.into_inner())
                                .unwrap();
                    });
                }
            });

            futures::future::join(read_inbound_packets, write_outbound_packets).await;
        });

    Ok(())
}
```

Needs proper error handling but the above works! This would primarily target Linux and thus only be useful for the Gateway. The benefit would be that we don't have to copy buffers for IP packets between userspace and kernel space.

The trickier part is the UDP IO. Currently, we are using `quinn-udp` for cross-platform high-performance IO. We also have GRO and GSO in place for improved performance. It is unclear how well those could be implemented with a completion-based IO runtime in a cross-platform way.

Potentially, they aren't needed though because most of the time is spent in copying buffers around so perhaps using completion-based IO would allow us to increase performance even without the batching from GSO/GRO.

We would still need to implement a certain variant of `RecvMsg` and `SendMsg` because we rely on the local socket address being known.

**Comment by thomaseizinger** [comment]
> The trickier part is the UDP IO. Currently, we are using `quinn-udp` for cross-platform high-performance IO. We also have GRO and GSO in place for improved performance. It is unclear how well those could be implemented with a completion-based IO runtime in a cross-platform way.
> 
> Potentially, they aren't needed though because most of the time is spent in copying buffers around so perhaps using completion-based IO would allow us to increase performance even without the batching from GSO/GRO.
> 
> We would still need to implement a certain variant of `RecvMsg` and `SendMsg` because we rely on the local socket address being known.

This has also been ported by `compio` already! https://github.com/compio-rs/compio/blob/master/compio-quic/src/socket.rs

**Comment by thomaseizinger** [comment]
> * GRO/GSO for TUN

I think there is some more performance to be gained here. We need to perform segmenation ourselves for that but that is reasonably easy:

- Stack-allocate the headers and use a shared, segmented buffer for the payloads
- Change the boringtun API to copy the packet directly into the dst buffer

**Comment by jamilbk** [comment]
Is io_uring relevant here for the Gateway?

**Comment by thomaseizinger** [comment]
> Is io_uring relevant here for the Gateway?

See above where I talk about completion-based runtimes :)

I don't know about io_uring for TUN device. Those are somewhat special file-descriptors so I am not sure if the existing io_uring syscalls work for it.

**Comment by thomaseizinger** [comment]
> * Multi-threaded UDP sockets with `SO_REUSEPORT`

Draft PR doing this for the Gateway here: https://github.com/firezone/firezone/pull/8873

**Comment by jamilbk** [comment]
Not as critical but TIL macOS (via kqueue) and even Windows have similar mechanisms to implement completion based io. Great article: https://tigerbeetle.com/blog/2022-11-23-a-friendly-abstraction-over-iouring-and-kqueue/

**Comment by thomaseizinger** [comment]
> Not as critical but TIL macOS (via kqueue) and even Windows have similar mechanisms to implement completion based io. Great article: https://tigerbeetle.com/blog/2022-11-23-a-friendly-abstraction-over-iouring-and-kqueue/

Yeah, the completion-based IO runtime I linked above supports all of these natively! That is why it would be a good fit because we could use it on all platforms! (I think Android would also support io-uring?)

**Comment by jamilbk** [comment]
Don't think Android will allow it due to security issues. https://www.phoronix.com/news/Google-Restricting-IO_uring

**Comment by thomaseizinger** [comment]
> Don't think Android will allow it due to security issues. https://www.phoronix.com/news/Google-Restricting-IO_uring

Dang, that is a no for us then or we need to find an abstraction to select the runtime per OS 🙄
